"""Add clarification tables and task pending fields

Revision ID: 0cef0a513109
Revises: 5a37eef8e789
Create Date: 2026-02-06 22:27:58.187996

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0cef0a513109"
down_revision: Union[str, Sequence[str], None] = "5a37eef8e789"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Add clarification_requests table
    op.create_table(
        "clarification_requests",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("run_id", sa.String(), nullable=False),
        sa.Column("task_id", sa.String(), nullable=False),
        sa.Column("attempt_num", sa.Integer(), nullable=False),
        sa.Column("questions", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("responded_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.ForeignKeyConstraint(["run_id"], ["runs.id"], ondelete="CASCADE"),
    )

    # Add indexes for clarification_requests
    op.create_index(op.f("ix_clarification_requests_run_id"), "clarification_requests", ["run_id"])
    op.create_index(
        op.f("ix_clarification_requests_task_id"), "clarification_requests", ["task_id"]
    )

    # Add clarification_responses table
    op.create_table(
        "clarification_responses",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("request_id", sa.String(), nullable=False),
        sa.Column("answers", sa.JSON(), nullable=False),
        sa.Column("responded_by", sa.String(), nullable=False),
        sa.Column("responded_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.ForeignKeyConstraint(["request_id"], ["clarification_requests.id"], ondelete="CASCADE"),
    )

    # Add unique constraint for request_id in responses
    op.create_index(
        op.f("ix_clarification_responses_request_id"),
        "clarification_responses",
        ["request_id"],
        unique=True,
    )

    # Add pending fields to tasks table
    with op.batch_alter_table("tasks", schema=None) as batch_op:
        batch_op.add_column(sa.Column("pending_action_type", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("pending_clarification_id", sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Drop pending fields from tasks table
    with op.batch_alter_table("tasks", schema=None) as batch_op:
        batch_op.drop_column("pending_clarification_id")
        batch_op.drop_column("pending_action_type")

    # Drop clarification_responses table and its indexes
    op.drop_index(
        op.f("ix_clarification_responses_request_id"), table_name="clarification_responses"
    )
    op.drop_table("clarification_responses")

    # Drop clarification_requests table and its indexes
    op.drop_index(op.f("ix_clarification_requests_task_id"), table_name="clarification_requests")
    op.drop_index(op.f("ix_clarification_requests_run_id"), table_name="clarification_requests")
    op.drop_table("clarification_requests")

    # ### end Alembic commands ###
