"""initial schema

Revision ID: 5a37eef8e789
Revises:
Create Date: 2026-02-06 15:57:19.735704

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5a37eef8e789"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Create runs table
    op.create_table(
        "runs",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("project_id", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("routine_id", sa.String(), nullable=True),
        sa.Column("routine_sha", sa.String(), nullable=True),
        sa.Column("routine_source", sa.String(), nullable=True),
        sa.Column("routine_embedded", sa.JSON(), nullable=True),
        sa.Column("agent_type", sa.String(), nullable=True),
        sa.Column("agent_config", sa.JSON(), nullable=False, default=dict),
        sa.Column("worktree_enabled", sa.Integer(), nullable=False, default=1),
        sa.Column("worktree_path", sa.String(), nullable=True),
        sa.Column("delete_worktree_on_completion", sa.Integer(), nullable=False, default=0),
        sa.Column("source_branch", sa.String(), nullable=True),
        sa.Column("merge_strategy", sa.String(), nullable=True),
        sa.Column("config", sa.JSON(), nullable=False, default=dict),
        sa.Column("env_file_specs", sa.JSON(), nullable=False, default=list),
        sa.Column("env_source_dir", sa.String(), nullable=True),
        sa.Column("current_step_index", sa.Integer(), nullable=False, default=0),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("agent_started_at", sa.DateTime(), nullable=True),
        sa.Column("total_tokens_read", sa.Integer(), nullable=False, default=0),
        sa.Column("total_tokens_write", sa.Integer(), nullable=False, default=0),
        sa.Column("total_tokens_cache", sa.Integer(), nullable=False, default=0),
        sa.Column("total_duration_ms", sa.Integer(), nullable=False, default=0),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_runs_project_id"), "runs", ["project_id"])
    op.create_index(op.f("ix_runs_status"), "runs", ["status"])

    # Create steps table
    op.create_table(
        "steps",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("run_id", sa.String(), nullable=False),
        sa.Column("config_id", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False, default=""),
        sa.Column("order_index", sa.Integer(), nullable=False),
        sa.Column("completed", sa.Integer(), nullable=False, default=0),
        sa.Column("human_approval", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.ForeignKeyConstraint(["run_id"], ["runs.id"], ondelete="CASCADE"),
    )

    # Create tasks table
    op.create_table(
        "tasks",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("step_id", sa.String(), nullable=False),
        sa.Column("config_id", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False, default=""),
        sa.Column("order_index", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(), nullable=False, default="pending"),
        sa.Column("checklist", sa.JSON(), nullable=False, default=list),
        sa.Column("current_attempt", sa.Integer(), nullable=False, default=0),
        sa.Column("max_attempts", sa.Integer(), nullable=False, default=3),
        sa.PrimaryKeyConstraint("id"),
        sa.ForeignKeyConstraint(["step_id"], ["steps.id"], ondelete="CASCADE"),
    )

    # Create attempts table
    op.create_table(
        "attempts",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("task_id", sa.String(), nullable=False),
        sa.Column("attempt_num", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("builder_prompt", sa.Text(), nullable=True),
        sa.Column("verifier_prompt", sa.Text(), nullable=True),
        sa.Column("verifier_comment", sa.Text(), nullable=True),
        sa.Column("outcome", sa.String(), nullable=True),
        sa.Column("tokens_read", sa.Integer(), nullable=False, default=0),
        sa.Column("tokens_write", sa.Integer(), nullable=False, default=0),
        sa.Column("tokens_cache", sa.Integer(), nullable=False, default=0),
        sa.Column("duration_ms", sa.Integer(), nullable=False, default=0),
        sa.Column("grade_snapshot", sa.JSON(), nullable=True),
        sa.Column("auto_verify_results", sa.JSON(), nullable=True),
        sa.Column("agent_type", sa.String(), nullable=True),
        sa.Column("agent_model", sa.String(), nullable=True),
        sa.Column("agent_settings", sa.JSON(), nullable=True),
        sa.Column("agent_output", sa.Text(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.ForeignKeyConstraint(["task_id"], ["tasks.id"], ondelete="CASCADE"),
    )

    # Create events table
    op.create_table(
        "events",
        sa.Column("id", sa.Integer(), nullable=False, autoincrement=True),
        sa.Column("run_id", sa.String(), nullable=False),
        sa.Column("event_type", sa.String(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.ForeignKeyConstraint(["run_id"], ["runs.id"], ondelete="CASCADE"),
    )
    op.create_index(op.f("ix_events_run_id"), "events", ["run_id"])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_events_run_id"), table_name="events")
    op.drop_table("events")
    op.drop_table("attempts")
    op.drop_table("tasks")
    op.drop_table("steps")
    op.drop_index(op.f("ix_runs_status"), table_name="runs")
    op.drop_index(op.f("ix_runs_project_id"), table_name="runs")
    op.drop_table("runs")
    # ### end Alembic commands ###
