"""add pending expansion requests table

Revision ID: ca739d2b9086
Revises: e5fe8c18b483
Create Date: 2026-03-12 00:30:44.875259

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "ca739d2b9086"  # pragma: allowlist secret
down_revision: Union[str, Sequence[str], None] = "e5fe8c18b483"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("agent_configs", schema=None) as batch_op:
        batch_op.create_unique_constraint("uq_agent_configs_name", ["name"])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("agent_configs", schema=None) as batch_op:
        batch_op.drop_constraint("uq_agent_configs_name", type_="unique")

    # ### end Alembic commands ###
