"""Compile authoritative GraphProjection inventory sites into anchored operation groups.

This is deliberately a compiler front end only: it never changes consumer source.
"""

from __future__ import annotations

import ast
from collections import Counter, defaultdict
from collections.abc import Iterable
from typing import Literal

import libcst as cst
from libcst.metadata import (
    MetadataWrapper,
    ParentNodeProvider,
    PositionProvider,
    QualifiedName,
    QualifiedNameProvider,
)
from pydantic import BaseModel, ConfigDict, field_validator, model_validator

from scripts.graph_projection_inventory import (
    AccessInventory,
    AccessKind,
    DiagnosticCode,
    InventorySource,
    ProjectionCallContext,
    QueryMigrationManifest,
    disposition_site_key,
    occurrence_id,
    source_digest,
)


SourceSnapshot = InventorySource
SiteOrigin = Literal["occurrence", "diagnostic"]


class AnchorRefusedError(ValueError):
    """Raised when an inventory identity cannot be proved against a source snapshot."""


class SourceLocator(BaseModel):
    """The CST position selected for a mechanically anchored operation."""

    model_config = ConfigDict(extra="forbid", frozen=True, strict=True)

    line: int
    column: int


class CstAnchorEvidence(BaseModel):
    """Recomputed proof used to select one source occurrence without source policy."""

    model_config = ConfigDict(extra="forbid", frozen=True, strict=True)

    node_type: str
    normalized_expression: str
    same_expression_ordinal: int
    context: ProjectionCallContext | None = None


class MigrationSite(BaseModel):
    """One source-anchored migration operation derived from inventory identity."""

    model_config = ConfigDict(extra="forbid", frozen=True, strict=True)

    origin: SiteOrigin
    original_site_id: str
    relative_path: str
    qualified_function: str
    access_kind: AccessKind | None
    old_field_name: str | None
    diagnostic_code: DiagnosticCode | None
    normalized_expression: str
    ordinal: int
    source_digest: str
    locator: SourceLocator
    anchor: CstAnchorEvidence
    parent_shape: str
    operation_shape: str

    @property
    def shape_key(self) -> str:
        return "|".join(
            (
                self.access_kind.value if self.access_kind is not None else "-",
                self.old_field_name or "-",
                self.diagnostic_code.value if self.diagnostic_code is not None else "-",
                self.parent_shape,
                self.operation_shape,
            )
        )


class OperationStream(BaseModel):
    """Deterministic, source-free operation stream grouped only by structural shape."""

    model_config = ConfigDict(extra="forbid", frozen=True, strict=True)

    sites: tuple[MigrationSite, ...]


def require_complete_receiver_physical_context(site: MigrationSite) -> None:
    """Refuse a query transform without collector-proven physical receiver facts."""
    context = site.anchor.context
    if (
        context is None
        or not context.projection_expression.strip()
        or context.projection_role != "receiver"
        or context.physical_old_field_name is None
        or context.physical_access_kind is None
        or context.physical_operation_shape is None
    ):
        raise AnchorRefusedError(
            "reviewed query transform lacks complete receiver physical context: "
            f"{site.original_site_id}"
        )


class PlannedOperation(BaseModel):
    """One reviewed ledger disposition joined to anchored operation IDs."""

    model_config = ConfigDict(extra="forbid", frozen=True, strict=True)

    disposition: Literal["query_transform", "approved_core", "projection_neutral"]
    reason: str
    consumed_site_ids: tuple[str, ...]
    shape_key: str

    @property
    def consumed_site_id_set(self) -> frozenset[str]:
        return frozenset(self.consumed_site_ids)

    @classmethod
    def _validate_consumed(cls, value: tuple[str, ...]) -> tuple[str, ...]:
        if not value:
            raise ValueError("consumed_site_ids must be nonempty")
        if len(value) != len(frozenset(value)):
            raise ValueError("consumed_site_ids must not repeat a site")
        return value

    @field_validator("reason")
    @classmethod
    def _reason_is_nonempty(cls, value: str) -> str:
        if not value.strip():
            raise ValueError("reason must be nonempty")
        return value

    _consumed_is_nonempty = field_validator("consumed_site_ids")(_validate_consumed)


class StructuralRuleOperation(BaseModel):
    """One finite rule application with the exact source evidence it consumed."""

    model_config = ConfigDict(extra="forbid", frozen=True, strict=True)

    site_id: str
    rule_id: str
    origin: str
    shape_key: str


class GeneratedFixtureOperation(BaseModel):
    """One deferred physical fixture operation generated by a finite rule."""

    model_config = ConfigDict(extra="forbid", frozen=True, strict=True)

    site_id: str
    rule_id: str
    shape_key: str
    evidence: tuple[tuple[str, str], ...]


class DispositionPlan(BaseModel):
    """Frozen exact-once compilation result for reviewed migration dispositions."""

    model_config = ConfigDict(extra="forbid", frozen=True, strict=True)

    operations: tuple[PlannedOperation, ...]
    reviewed_deferred_site_ids: tuple[str, ...]
    generated_fixture_operations: tuple[GeneratedFixtureOperation, ...]
    pending_site_ids: tuple[str, ...]
    disposition_counts: tuple[tuple[str, int], ...]
    shape_group_counts: tuple[tuple[str, int], ...]
    neutral_rule_operations: tuple[StructuralRuleOperation, ...] = ()
    rule_family_counts: tuple[tuple[str, int], ...]
    symbol_origin_counts: tuple[tuple[str, int], ...]
    generated_fixture_family_counts: tuple[tuple[str, int], ...]

    @property
    def consumed_site_ids(self) -> frozenset[str]:
        return frozenset(
            site_id for operation in self.operations for site_id in operation.consumed_site_ids
        )

    @property
    def generated_fixture_site_ids(self) -> frozenset[str]:
        return frozenset(item.site_id for item in self.generated_fixture_operations)

    @property
    def fixture_site_ids(self) -> frozenset[str]:
        return frozenset(self.reviewed_deferred_site_ids) | self.generated_fixture_site_ids

    @property
    def deferred_site_ids(self) -> tuple[str, ...]:
        return tuple(sorted(self.fixture_site_ids))

    @model_validator(mode="after")
    def _validate_total_partition(self) -> "DispositionPlan":
        consumed = [
            site_id for operation in self.operations for site_id in operation.consumed_site_ids
        ]
        if len(consumed) != len(frozenset(consumed)):
            raise ValueError("planned operation consumed-site sets overlap")
        deferred = set(self.reviewed_deferred_site_ids)
        generated_fixture_ids = [item.site_id for item in self.generated_fixture_operations]
        pending = set(self.pending_site_ids)
        if (
            len(deferred) != len(self.reviewed_deferred_site_ids)
            or len(generated_fixture_ids) != len(frozenset(generated_fixture_ids))
            or len(pending) != len(self.pending_site_ids)
        ):
            raise ValueError("deferred and pending site IDs must be unique")
        generated = set(generated_fixture_ids)
        if (
            deferred & generated
            or deferred & pending
            or generated & pending
            or self.fixture_site_ids & set(consumed)
            or pending & set(consumed)
        ):
            raise ValueError("plan partitions overlap")
        if not self.disposition_counts or not self.shape_group_counts:
            raise ValueError("derived plan counts must be nonempty")
        if self.disposition_counts != tuple(
            sorted(Counter(item.disposition for item in self.operations).items())
        ):
            raise ValueError("disposition counts do not match operations")
        if self.shape_group_counts != tuple(
            sorted(Counter(item.shape_key for item in self.operations).items())
        ):
            raise ValueError("shape counts do not match operations")
        rule_ids = [item.site_id for item in self.neutral_rule_operations]
        neutral_ids = {
            item.consumed_site_ids[0]
            for item in self.operations
            if item.disposition == "projection_neutral"
        }
        if len(rule_ids) != len(frozenset(rule_ids)) or (
            (not self.pending_site_ids or self.neutral_rule_operations)
            and set(rule_ids) != neutral_ids
        ):
            raise ValueError("neutral rule operations do not match neutral operations")
        if self.rule_family_counts != tuple(
            sorted(Counter(item.rule_id for item in self.neutral_rule_operations).items())
        ):
            raise ValueError("rule family counts do not match rule operations")
        if self.symbol_origin_counts != tuple(
            sorted(Counter(item.origin for item in self.neutral_rule_operations).items())
        ):
            raise ValueError("symbol origin counts do not match rule operations")
        if self.generated_fixture_family_counts != tuple(
            sorted(Counter(item.rule_id for item in self.generated_fixture_operations).items())
        ):
            raise ValueError("generated fixture family counts do not match fixture operations")
        if any(
            count < 0
            for _, count in (
                *self.rule_family_counts,
                *self.symbol_origin_counts,
                *self.generated_fixture_family_counts,
            )
        ):
            raise ValueError("derived counts must be nonnegative")
        return self


class QueryCompositionGroup(BaseModel):
    """One immutable outer-CST action that consumes reviewed transform anchors."""

    model_config = ConfigDict(extra="forbid", frozen=True, strict=True)

    relative_path: str
    source_span: tuple[int, int, int, int]
    outer_action_id: str
    owner_site_id: str | None
    owner_anchor: CstAnchorEvidence
    original_outer_expression: str
    consumed_site_ids: tuple[str, ...]
    anchor_relations: tuple[tuple[str, str], ...]

    @model_validator(mode="after")
    def _validate_group(self) -> "QueryCompositionGroup":
        if not self.relative_path.strip() or not self.original_outer_expression.strip():
            raise ValueError("composition paths and expressions must be nonblank")
        start = self.source_span[:2]
        end = self.source_span[2:]
        if start[0] < 1 or end[0] < 1 or start[1] < 0 or end[1] < 0 or start >= end:
            raise ValueError("composition source span must be positive and ordered")
        if not self.outer_action_id.strip():
            raise ValueError("composition outer action owner must be nonblank")
        expected_owner = (
            f"outer:{self.relative_path}:{':'.join(str(value) for value in self.source_span)}"
        )
        if self.outer_action_id != expected_owner:
            raise ValueError("composition outer action owner must match its path and span")
        try:
            outer = cst.parse_expression(self.original_outer_expression)
        except cst.ParserSyntaxError as error:
            raise ValueError("composition outer expression must parse") from error
        if (
            type(outer).__name__ != self.owner_anchor.node_type
            or _normalized_node(outer) != self.owner_anchor.normalized_expression
            or self.owner_anchor.same_expression_ordinal != 0
        ):
            raise ValueError("composition outer anchor must match its expression")
        if (
            not self.consumed_site_ids
            or tuple(sorted(self.consumed_site_ids)) != self.consumed_site_ids
            or len(self.consumed_site_ids) != len(frozenset(self.consumed_site_ids))
            or any(not site_id.strip() for site_id in self.consumed_site_ids)
        ):
            raise ValueError(
                "composition group consumed site IDs must be canonical, nonempty and unique"
            )
        if self.owner_site_id is not None and self.owner_site_id not in self.consumed_site_ids:
            raise ValueError("composition site owner must be consumed")
        if (
            tuple(sorted(self.anchor_relations)) != self.anchor_relations
            or len(self.anchor_relations) != len(frozenset(self.anchor_relations))
            or any(
                ancestor == descendant
                or ancestor not in self.consumed_site_ids
                or descendant not in self.consumed_site_ids
                for ancestor, descendant in self.anchor_relations
            )
        ):
            raise ValueError(
                "composition anchor relations must be canonical, unique consumed ancestry pairs"
            )
        if self.owner_site_id is not None:
            # Additional actual nested relations are valid, but the outer site
            # itself must prove ownership of every other consumed anchor.
            missing = {
                (self.owner_site_id, site_id)
                for site_id in self.consumed_site_ids
                if site_id != self.owner_site_id
            } - set(self.anchor_relations)
            if missing:
                raise ValueError("a site owner must relate to every descendant anchor")
        children: dict[str, set[str]] = defaultdict(set)
        for ancestor, descendant in self.anchor_relations:
            children[ancestor].add(descendant)
        for start in self.consumed_site_ids:
            pending = list(children[start])
            seen: set[str] = set()
            while pending:
                descendant = pending.pop()
                if descendant == start:
                    raise ValueError("composition anchor relations must be acyclic")
                if descendant not in seen:
                    seen.add(descendant)
                    pending.extend(children[descendant])
        return self


class QueryCompositionPlan(BaseModel):
    """Frozen, exact-once source ownership partition for reviewed query transforms."""

    model_config = ConfigDict(extra="forbid", frozen=True, strict=True)

    groups: tuple[QueryCompositionGroup, ...]

    @property
    def consumed_site_ids(self) -> frozenset[str]:
        return frozenset(site_id for group in self.groups for site_id in group.consumed_site_ids)

    @model_validator(mode="after")
    def _validate_plan(self) -> "QueryCompositionPlan":
        consumed = [site_id for group in self.groups for site_id in group.consumed_site_ids]
        if len(consumed) != len(frozenset(consumed)):
            raise ValueError("composition groups overlap by consumed site ID")
        for index, group in enumerate(self.groups):
            for other in self.groups[index + 1 :]:
                if group.relative_path == other.relative_path and _spans_overlap(
                    group.source_span, other.source_span
                ):
                    raise ValueError("composition groups overlap by source action span")
        if self.groups != tuple(
            sorted(
                self.groups,
                key=lambda group: (group.relative_path, group.source_span, group.outer_action_id),
            )
        ):
            raise ValueError("composition groups must be canonically ordered")
        return self


def _spans_overlap(left: tuple[int, int, int, int], right: tuple[int, int, int, int]) -> bool:
    return left[:2] < right[2:] and right[:2] < left[2:]


def _outer_action(node: cst.CSTNode, parents: dict[cst.CSTNode, cst.CSTNode]) -> cst.CSTNode:
    """Walk all CST bridge nodes to the enclosing statement action boundary."""
    outer = node if isinstance(node, cst.BaseExpression) else None
    current = node
    while (parent := parents.get(current)) is not None:
        if isinstance(parent, cst.BaseStatement):
            if outer is None:
                break
            return outer
        # LibCST bridge nodes (Arg, Element, DictElement, SubscriptElement,
        # Index, ComparisonTarget and comprehension clauses) deliberately do
        # not terminate the walk; their enclosing expression is the action.
        if isinstance(parent, cst.BaseExpression):
            outer = parent
        current = parent
    raise AnchorRefusedError(f"unsupported outer action boundary: {type(current).__name__}")


def _is_ancestor(
    ancestor: cst.CSTNode,
    descendant: cst.CSTNode,
    parents: dict[cst.CSTNode, cst.CSTNode],
) -> bool:
    current = parents.get(descendant)
    while current is not None:
        if current is ancestor:
            return True
        current = parents.get(current)
    return False


def _reanchor_operation_stream_site(
    site: MigrationSite,
    *,
    occurrence_nodes: tuple[cst.CSTNode, ...] | None,
    diagnostic_nodes: tuple[cst.CSTNode, ...] | None,
    parents: dict[cst.CSTNode, cst.CSTNode],
    positions: dict[cst.CSTNode, object],
    qualified_names: dict[cst.CSTNode, object],
) -> cst.CSTNode:
    """Reanchor one stream identity using the same origin-specific proof as collection."""
    if site.origin == "occurrence":
        if site.access_kind is None or occurrence_nodes is None:
            raise AnchorRefusedError(f"occurrence lacks access kind: {site.original_site_id}")
        if site.ordinal >= len(occurrence_nodes):
            raise AnchorRefusedError(f"missing occurrence CST anchor: {site.original_site_id}")
        node = occurrence_nodes[site.ordinal]
    else:
        if diagnostic_nodes is None or site.ordinal >= len(diagnostic_nodes):
            raise AnchorRefusedError(f"missing diagnostic CST anchor: {site.original_site_id}")
        node = diagnostic_nodes[site.ordinal]
        position = positions[node].start
        if (
            position.line != site.locator.line
            or type(node).__name__ != site.anchor.node_type
            or (_normalized_node(node) or cst.Module([]).code_for_node(node).strip())
            != site.anchor.normalized_expression
        ):
            raise AnchorRefusedError(f"diagnostic identity mismatch: {site.original_site_id}")
    if (
        _anchor_evidence(
            node,
            normalized_expression=site.anchor.normalized_expression,
            ordinal=site.anchor.same_expression_ordinal,
            stored_context=site.anchor.context,
            qualified_names=qualified_names,
            parents=parents,
            expected_access_kind=site.access_kind,
        )
        != site.anchor
    ):
        raise AnchorRefusedError(f"query rewrite anchor evidence mismatch: {site.original_site_id}")
    return node


def _reanchor_operation_stream_sites(
    sources: Iterable[SourceSnapshot], sites: Iterable[MigrationSite]
) -> dict[
    str, tuple[cst.CSTNode, dict[cst.CSTNode, cst.CSTNode], dict[cst.CSTNode, object], cst.Module]
]:
    """Prove stream identities against snapshots for every consumer of stream anchors."""
    sites = tuple(sites)
    snapshots = _source_map(sources)
    grouped: dict[str, list[MigrationSite]] = defaultdict(list)
    for site in sites:
        grouped[site.relative_path].append(site)
    anchored: dict[
        str,
        tuple[cst.CSTNode, dict[cst.CSTNode, cst.CSTNode], dict[cst.CSTNode, object], cst.Module],
    ] = {}
    for path, path_sites in grouped.items():
        snapshot = snapshots.get(path)
        if snapshot is None or source_digest(snapshot.source) != path_sites[0].source_digest:
            raise AnchorRefusedError(f"digest mismatch: {path}")
        if any(site.source_digest != path_sites[0].source_digest for site in path_sites):
            raise AnchorRefusedError(f"inconsistent stream source digest: {path}")
        module = cst.parse_module(snapshot.source)
        candidates, parents, positions, qualified, qualified_names = _node_candidates(module)
        scope_lines = _scope_lines(module, positions, qualified)
        for site in path_sites:
            occurrence_nodes: tuple[cst.CSTNode, ...] | None = None
            diagnostic_nodes: tuple[cst.CSTNode, ...] | None = None
            if site.origin == "occurrence":
                peers = [
                    item
                    for item in path_sites
                    if item.origin == "occurrence"
                    and item.qualified_function == site.qualified_function
                    and item.normalized_expression == site.normalized_expression
                ]
                nodes = _matching_occurrence_nodes(
                    candidates=candidates,
                    parents=parents,
                    qualified_function=site.qualified_function,
                    normalized_expression=site.normalized_expression,
                    access_kinds=tuple(
                        item.access_kind for item in peers if item.access_kind is not None
                    ),
                )
                if sorted(item.ordinal for item in peers) != list(range(len(nodes))):
                    raise AnchorRefusedError(
                        f"ambiguous occurrence anchor: {site.original_site_id}"
                    )
                occurrence_nodes = nodes
            else:
                if site.diagnostic_code is None:
                    raise AnchorRefusedError(f"diagnostic lacks code: {site.original_site_id}")
                peers = [
                    item
                    for item in path_sites
                    if item.origin == "diagnostic"
                    and item.qualified_function == site.qualified_function
                    and item.diagnostic_code is site.diagnostic_code
                    and item.normalized_expression == site.normalized_expression
                ]
                diagnostic_nodes = _matching_diagnostic_nodes(
                    source=snapshot.source,
                    module=module,
                    positions=positions,
                    scope_lines=scope_lines,
                    qualified_function=site.qualified_function,
                    code=site.diagnostic_code,
                    normalized_source_pattern=site.normalized_expression,
                    signatures=tuple(
                        (item.anchor.node_type, item.anchor.normalized_expression) for item in peers
                    ),
                )
                if sorted(item.ordinal for item in peers) != list(range(len(diagnostic_nodes))):
                    raise AnchorRefusedError(
                        f"ambiguous diagnostic anchor: {site.original_site_id}"
                    )
            node = _reanchor_operation_stream_site(
                site,
                occurrence_nodes=occurrence_nodes,
                diagnostic_nodes=diagnostic_nodes,
                parents=parents,
                positions=positions,
                qualified_names=qualified_names,
            )
            if site.origin == "diagnostic" and qualified[id(node)] != site.qualified_function:
                raise AnchorRefusedError(f"diagnostic scope mismatch: {site.original_site_id}")
            anchored[site.original_site_id] = (node, parents, positions, module)
    if len(anchored) != len(sites):
        raise AnchorRefusedError("duplicate stream site identity during reanchoring")
    return anchored


def compile_query_composition_plan(
    sources: Iterable[SourceSnapshot], stream: OperationStream, plan: DispositionPlan
) -> QueryCompositionPlan:
    """Reanchor reviewed transforms and partition their recognized outer CST actions."""
    sites = {site.original_site_id: site for site in stream.sites}
    if len(sites) != len(stream.sites):
        raise AnchorRefusedError("duplicate query composition operation-stream site identity")
    ids = tuple(
        sorted(
            site_id
            for operation in plan.operations
            if operation.disposition == "query_transform"
            for site_id in operation.consumed_site_ids
        )
    )
    if len(ids) != len(frozenset(ids)) or any(site_id not in sites for site_id in ids):
        raise AnchorRefusedError("query composition disposition IDs are missing or overlapping")
    # Reanchor the complete stream: occurrence cardinality is an identity proof
    # over all like candidates, not merely the disposition-selected subset.
    anchored = _reanchor_operation_stream_sites(sources, stream.sites)
    actions: list[tuple[str, tuple[int, int, int, int], cst.CSTNode, str]] = []
    for site_id in ids:
        node, parents, positions, _ = anchored[site_id]
        outer = _outer_action(node, parents)
        position = positions[outer]
        actions.append(
            (
                sites[site_id].relative_path,
                (
                    position.start.line,
                    position.start.column,
                    position.end.line,
                    position.end.column,
                ),
                outer,
                site_id,
            )
        )
    components: list[list[tuple[str, tuple[int, int, int, int], cst.CSTNode, str]]] = []
    for action in sorted(actions, key=lambda item: (item[0], item[1], item[3])):
        matching = [
            component
            for component in components
            if any(
                member[0] == action[0] and _spans_overlap(member[1], action[1])
                for member in component
            )
        ]
        if not matching:
            components.append([action])
        else:
            merged = [action, *(member for component in matching for member in component)]
            components = [component for component in components if component not in matching]
            components.append(merged)
    groups: list[QueryCompositionGroup] = []
    for component in components:
        path = component[0][0]
        spans = {item[1] for item in component}
        if len(spans) != 1:
            raise AnchorRefusedError("incomparable overlapping outer actions")
        span = next(iter(spans))
        outer = component[0][2]
        if any(item[2] is not outer for item in component):
            raise AnchorRefusedError("ambiguous outer action identity")
        consumed = tuple(sorted(item[3] for item in component))
        node_by_id = {site_id: anchored[site_id][0] for site_id in consumed}
        owner = next((site_id for site_id in consumed if node_by_id[site_id] is outer), None)
        relations = tuple(
            sorted(
                (ancestor, descendant)
                for ancestor, ancestor_node in node_by_id.items()
                for descendant, descendant_node in node_by_id.items()
                if ancestor != descendant
                and _is_ancestor(ancestor_node, descendant_node, anchored[ancestor][1])
            )
        )
        _, _, _, module = anchored[consumed[0]]
        groups.append(
            QueryCompositionGroup(
                relative_path=path,
                source_span=span,
                outer_action_id=f"outer:{path}:{':'.join(str(value) for value in span)}",
                owner_site_id=owner,
                owner_anchor=CstAnchorEvidence(
                    node_type=type(outer).__name__,
                    normalized_expression=(
                        _normalized_node(outer) or module.code_for_node(outer).strip()
                    ),
                    same_expression_ordinal=0,
                ),
                original_outer_expression=module.code_for_node(outer).strip(),
                consumed_site_ids=consumed,
                anchor_relations=relations,
            )
        )
    result = QueryCompositionPlan(groups=tuple(groups))
    if (ids and not result.groups) or result.consumed_site_ids != frozenset(ids):
        raise AnchorRefusedError("query composition groups do not close reviewed IDs")
    return result


_GRAPH_ORIGIN = "orchestrator.graph"
_PROJECTION_FACTORIES = frozenset(
    {
        "orchestrator.graph.initial_projection",
        "orchestrator.graph.build_projection",
        "orchestrator.graph.reduce_event",
        "orchestrator.graph.projection_from_checkpoint",
        "orchestrator.graph_runtime.controller.rebuild_projection",
        "orchestrator.graph.projections.reduce_event",
    }
)
_PUBLIC_PROJECTION_ARGUMENT_POSITIONS = {
    "orchestrator.graph.callbacks.validate_callback": frozenset({1}),
    "orchestrator.graph.patch_validator.validate_patch": frozenset({3}),
    "orchestrator.graph.projections.final_invariant_blockers_for_events": frozenset({1}),
}
_PUBLIC_PROJECTION_CALLS = frozenset(
    {
        "orchestrator.graph.verifier_verdict",
        "orchestrator.graph.recovery_nodes_for_record",
        "orchestrator.graph.invalid_test_blocks",
        "orchestrator.graph.check_results",
        "orchestrator.graph.passed_verification_result",
        "orchestrator.graph.failed_verification_result",
        "orchestrator.graph.node_usage_recorded",
        "orchestrator.graph.recovery_nodes",
        "orchestrator.graph.passed_verification_results",
        "orchestrator.graph.latest_routine_snapshot_record",
        "orchestrator.graph.failed_verification_results",
        "orchestrator.graph.accepted_output_records_for_node_port",
        "orchestrator.graph.check_result",
        "orchestrator.graph.invalid_test_block",
        "orchestrator.graph.failed_verification_candidate_ids",
        "orchestrator.graph.authority_revision_blocker",
        "orchestrator.graph.gate_decision",
        "orchestrator.graph.node_gate_decision",
        "orchestrator.graph.decision_request",
        "orchestrator.graph.configured_gates",
        "orchestrator.graph.node_states",
        "orchestrator.graph.task_states",
        "orchestrator.graph.passed_verification_candidate_ids",
        "orchestrator.graph.oversight_decision",
        "orchestrator.graph.accepted_output_records",
        "orchestrator.graph.environment_failure",
        "orchestrator.graph.support_evidence",
        "orchestrator.graph.accepted_no_successor_patch_id",
        "orchestrator.graph.accepted_no_successor_patch_ids",
        "orchestrator.graph.environment_failures",
        "orchestrator.graph.planner_generation_budget",
        "orchestrator.graph.accepted_graph_patch_ids",
        "orchestrator.graph.requirement_revision",
        "orchestrator.graph.project_leases",
        "orchestrator.graph.project_node_states",
        "orchestrator.graph.run_state",
        "orchestrator.graph.project_scheduler_view",
        "orchestrator.graph.completion_decision_passed",
        "orchestrator.graph.projection_to_checkpoint",
        "orchestrator.graph.project_node_metadata",
        "orchestrator.graph.project_lease_view",
        "orchestrator.graph.project_final_invariant_blockers",
        "orchestrator.graph.project_run_state",
        "orchestrator.graph.project_task_states",
        "orchestrator.graph.project_ready_nodes",
        "orchestrator.graph.project_decision_view_from_projection",
        "orchestrator.graph.projection_queries.resource_claims_for_node",
        "orchestrator.graph.project_graph_projection_snapshot",
        "orchestrator.graph.project_decision_view",
        "orchestrator.graph.callbacks.validate_callback",
        "orchestrator.graph.patch_validator.validate_patch",
        "orchestrator.graph.projections.final_invariant_blockers_for_events",
    }
)
_DERIVED_VALUE_SINKS = frozenset({"orchestrator.graph.scheduler.NodeScheduleInfo"})
_APPROVED_CORE_PATHS = frozenset(
    {
        "src/orchestrator/graph/projection_models.py",
        "src/orchestrator/graph/projection_collections.py",
        "src/orchestrator/graph/projection_queries.py",
        "src/orchestrator/graph/projection_codec.py",
        "src/orchestrator/graph/projections.py",
    }
)
_GRAPH_PROJECTION_ORIGINS = frozenset(
    {
        "orchestrator.graph.GraphProjection",
        "orchestrator.graph._commands.GraphProjection",
        "orchestrator.graph.projections.GraphProjection",
    }
)
_APPROVED_CORE_READ_SHAPES = frozenset(
    {
        "subscript_read",
        "literal_subscript_read",
        "map_get",
        "keys_iteration",
        "values_iteration",
        "items_iteration",
        "membership",
        "nested_get",
        "items",
        "values",
    }
)


def _approved_import_origin(name: QualifiedName | None) -> str | None:
    if name is None or name.source.name != "IMPORT":
        return None
    if name.name.rpartition(".")[0] in {
        "orchestrator.graph",
        "orchestrator.graph.callbacks",
        "orchestrator.graph._commands",
        "orchestrator.graph.patch_validator",
        "orchestrator.graph.projections",
        "orchestrator.graph.projection_queries",
        "orchestrator.graph.scheduler",
        "orchestrator.graph_runtime",
        "orchestrator.graph_runtime.controller",
        "orchestrator.graph_runtime.dispatch",
    }:
        return name.name
    return None


def _is_projection_factory(origin: str | None) -> bool:
    return origin in _PROJECTION_FACTORIES


def _resolved_qualified_names(
    node: cst.CSTNode, qualified_names: dict[cst.CSTNode, object]
) -> frozenset[QualifiedName]:
    value = qualified_names.get(node, frozenset())
    resolved = value() if callable(value) else value
    if not isinstance(resolved, set):
        return frozenset()
    return frozenset(item for item in resolved if isinstance(item, QualifiedName))


def _one_qualified_name(
    node: cst.CSTNode, qualified_names: dict[cst.CSTNode, object]
) -> QualifiedName | None:
    names = _resolved_qualified_names(node, qualified_names)
    return next(iter(names)) if len(names) == 1 else None


def _literal_subscript_field(node: cst.Subscript) -> str | None:
    if (
        len(node.slice) != 1
        or not isinstance((element := node.slice[0]).slice, cst.Index)
        or not isinstance(element.slice.value, cst.SimpleString)
    ):
        return None
    return element.slice.value.evaluated_value


def _literal_argument_field(arguments: tuple[cst.Arg, ...]) -> str | None:
    if not arguments or not isinstance(arguments[0].value, cst.SimpleString):
        return None
    return arguments[0].value.evaluated_value


def _root_subscript(node: cst.Subscript) -> cst.Subscript:
    current = node
    while isinstance(current.value, cst.Subscript):
        current = current.value
    return current


def _physical_signature(
    node: cst.CSTNode, parents: dict[cst.CSTNode, cst.CSTNode]
) -> tuple[str, str | None, AccessKind, str] | None:
    """Derive one physical operation from its exact CST action and receiver."""
    if isinstance(node, cst.Del) and isinstance(node.target, cst.Subscript):
        physical_target = _root_subscript(node.target)
        field = _literal_subscript_field(physical_target)
        receiver = _normalized_node(node.target.value)
        if field is not None and receiver is not None:
            return receiver, field, AccessKind.DELETE_POP, AccessKind.DELETE_POP.value
        return None
    if isinstance(node, cst.Comparison) and len(node.comparisons) == 1:
        comparison = node.comparisons[0]
        if isinstance(comparison.operator, (cst.In, cst.NotIn)):
            receiver = _normalized_node(comparison.comparator)
            if isinstance(node.left, cst.SimpleString) and receiver is not None:
                return (
                    receiver,
                    node.left.evaluated_value,
                    AccessKind.MEMBERSHIP,
                    AccessKind.MEMBERSHIP.value,
                )
    if isinstance(node, cst.Subscript):
        if isinstance(parents[node], cst.Del):
            return None
        field = _literal_subscript_field(_root_subscript(node))
        receiver = _normalized_node(node.value)
        if field is None or receiver is None:
            return None
        parent = parents[node]
        if isinstance(parent, cst.AssignTarget) or (
            isinstance(parent, cst.AnnAssign) and parent.target is node
        ):
            kind = (
                AccessKind.NESTED_ASSIGNMENT
                if isinstance(node.value, cst.Subscript)
                else AccessKind.DIRECT_ASSIGNMENT
            )
        else:
            kind = AccessKind.LITERAL_SUBSCRIPT_READ
        return receiver, field, kind, kind.value
    if not isinstance(node, cst.Call) or not isinstance(node.func, cst.Attribute):
        return None
    method = node.func.attr.value
    receiver = node.func.value
    receiver_expression = _normalized_node(receiver)
    if receiver_expression is None:
        return None
    if isinstance(receiver, cst.Subscript) and method not in {"append", "extend"}:
        field = _literal_subscript_field(_root_subscript(receiver))
        if field is not None:
            return (
                receiver_expression,
                field,
                AccessKind.LITERAL_SUBSCRIPT_READ,
                AccessKind.LITERAL_SUBSCRIPT_READ.value,
            )
    direct_methods = {
        "get": AccessKind.GET,
        "pop": AccessKind.DELETE_POP,
        "setdefault": AccessKind.SETDEFAULT,
        "keys": AccessKind.KEYS,
        "values": AccessKind.VALUES,
        "items": AccessKind.ITEMS,
    }
    if method in direct_methods:
        field = (
            None if method in {"keys", "values", "items"} else _literal_argument_field(node.args)
        )
        if method in {"keys", "values", "items"} or field is not None:
            kind = direct_methods[method]
            return receiver_expression, field, kind, kind.value
        return None
    if method not in {"append", "extend"}:
        return None
    if isinstance(receiver, cst.Subscript):
        field = _literal_subscript_field(receiver)
    elif (
        isinstance(receiver, cst.Call)
        and isinstance(receiver.func, cst.Attribute)
        and receiver.func.attr.value == "get"
    ):
        field = _literal_argument_field(receiver.args)
    else:
        field = None
    if field is None:
        return None
    return receiver_expression, field, AccessKind.APPEND_EXTEND, AccessKind.APPEND_EXTEND.value


def _reanchor_context(
    node: cst.CSTNode,
    stored: ProjectionCallContext | None,
    qualified_names: dict[cst.CSTNode, object],
    parents: dict[cst.CSTNode, cst.CSTNode],
    expected_access_kind: AccessKind | None = None,
) -> ProjectionCallContext | None:
    """Revalidate stored collector context without discovering projection values."""
    if stored is None:
        return None
    if stored.physical_access_kind is not None:
        if stored.projection_role != "receiver":
            raise AnchorRefusedError("inventory physical context does not match CST anchor")
        signatures = [signature for signature in (_physical_signature(node, parents),) if signature]

        class PhysicalVisitor(cst.CSTVisitor):
            def on_visit(_, child: cst.CSTNode) -> bool:
                if (
                    child is not node
                    and (signature := _physical_signature(child, parents)) is not None
                ):
                    signatures.append(signature)
                return True

        node.visit(PhysicalVisitor())
        if not signatures:
            raise AnchorRefusedError("inventory physical context does not match CST anchor")
        matching_signatures = [
            signature
            for signature in signatures
            if signature[0] == stored.projection_expression
            and signature[1] == stored.physical_old_field_name
            and signature[2] is stored.physical_access_kind
            and signature[3] == stored.physical_operation_shape
        ]
        if len(matching_signatures) == 1:
            receiver, field, access_kind, operation_shape = matching_signatures[0]
            if expected_access_kind is not None and expected_access_kind is not access_kind:
                raise AnchorRefusedError("inventory physical access kind does not match CST anchor")
            return stored
        receiver_matches = [
            signature for signature in signatures if signature[0] == stored.projection_expression
        ]
        if not receiver_matches:
            raise AnchorRefusedError("inventory projection expression does not match CST anchor")
        if len(receiver_matches) != 1:
            raise AnchorRefusedError("inventory physical context does not match CST anchor")
        _, field, access_kind, operation_shape = receiver_matches[0]
        if (
            expected_access_kind is not None
            and expected_access_kind is not access_kind
            or stored.physical_access_kind is not access_kind
        ):
            raise AnchorRefusedError("inventory physical access kind does not match CST anchor")
        if stored.physical_old_field_name != field:
            raise AnchorRefusedError("inventory physical context does not match CST anchor")
        if stored.physical_operation_shape != operation_shape:
            raise AnchorRefusedError("inventory physical operation shape does not match CST anchor")
        raise AnchorRefusedError("inventory physical context does not match CST anchor")
    if isinstance(node, cst.Param):
        annotation = node.annotation.annotation if node.annotation is not None else None
        name = _one_qualified_name(annotation, qualified_names) if annotation is not None else None
        origin = _approved_import_origin(name)
        if stored.receiver_type_origin != origin:
            raise AnchorRefusedError("inventory type context does not match CST anchor")
        if stored.projection_expression != _normalized_node(node.name):
            raise AnchorRefusedError("inventory projection expression does not match CST anchor")
        return stored
    direct_call = (
        node
        if isinstance(node, cst.Call)
        else node.value
        if isinstance(node, (cst.Assign, cst.AnnAssign, cst.Return))
        and isinstance(node.value, cst.Call)
        else None
    )
    calls = [direct_call] if direct_call is not None else []
    if isinstance(node, cst.Comparison):

        class CallVisitor(cst.CSTVisitor):
            def visit_Call(self, call: cst.Call) -> None:
                calls.append(call)

        node.visit(CallVisitor())
    if not calls:
        if stored.callee_origin is not None or stored.projection_role != "receiver":
            raise AnchorRefusedError("inventory call context does not match CST anchor")
        receiver = node.value if isinstance(node, cst.Subscript) else node
        if stored.projection_expression != _normalized_node(receiver):
            raise AnchorRefusedError("inventory projection expression does not match CST anchor")
        return stored
    matching_calls = []
    for call in calls:
        name = _one_qualified_name(call.func, qualified_names)
        origin = _approved_import_origin(name)
        if origin == stored.callee_origin:
            matching_calls.append(call)
    if len(matching_calls) != 1:
        raise AnchorRefusedError(
            "inventory callee context does not match CST anchor: "
            f"{stored.callee_origin!r} at {cst.Module([]).code_for_node(node).strip()!r}"
        )
    call = matching_calls[0]
    if stored.projection_role == "receiver":
        receiver = call.func.value if isinstance(call.func, cst.Attribute) else call
        if stored.projection_expression != _normalized_node(receiver):
            raise AnchorRefusedError("inventory receiver context does not match CST anchor")
        return stored
    elif stored.projection_role == "positional":
        positional_arguments = [
            argument for argument in call.args if argument.keyword is None and not argument.star
        ]
        if (
            stored.positional_index is None
            or stored.positional_index >= len(positional_arguments)
            or any(
                argument.star == "*"
                for argument in call.args[
                    : call.args.index(positional_arguments[stored.positional_index])
                ]
            )
        ):
            raise AnchorRefusedError("inventory positional context does not match CST anchor")
        if stored.projection_expression != _normalized_node(
            positional_arguments[stored.positional_index].value
        ):
            raise AnchorRefusedError("inventory positional expression does not match CST anchor")
    elif stored.projection_role == "keyword":
        matching_arguments = [
            argument
            for argument in call.args
            if argument.keyword is not None and argument.keyword.value == stored.keyword_name
        ]
        if len(matching_arguments) != 1 or stored.projection_expression != _normalized_node(
            matching_arguments[0].value
        ):
            raise AnchorRefusedError("inventory keyword context does not match CST anchor")
    elif stored.projection_role == "ambiguous":
        matching_arguments = (
            [
                argument
                for argument in call.args
                if argument.star == stored.argument_star
                and stored.projection_expression == _normalized_node(argument.value)
            ]
            if stored.argument_star
            else [
                argument
                for index, argument in enumerate(call.args)
                if not argument.star
                and stored.projection_expression == _normalized_node(argument.value)
                and any(item.star == stored.preceding_star for item in call.args[:index])
            ]
        )
        if len(matching_arguments) != 1:
            raise AnchorRefusedError("inventory ambiguous context does not match CST anchor")
    elif stored.projection_role == "derived_value":
        matching_arguments = [
            argument
            for argument in call.args
            if stored.projection_expression == _normalized_node(argument.value)
        ]
        if len(matching_arguments) != 1:
            raise AnchorRefusedError("inventory derived-value context does not match CST anchor")
    return stored


def plan_reviewed_dispositions(
    stream: OperationStream, manifest: QueryMigrationManifest
) -> DispositionPlan:
    """Compile reviewed ledger records to exact-once in-memory operations.

    This boundary deliberately uses ledger identities only to reconcile them to
    the already-anchored stream; it selects no transformation policy.
    """
    stream_by_id = {site.original_site_id: site for site in stream.sites}
    if len(stream_by_id) != len(stream.sites):
        raise AnchorRefusedError("duplicate anchored operation-stream site identity")
    reviewed_ids = {item.site_key for item in manifest.dispositions}
    missing = reviewed_ids - stream_by_id.keys()
    if missing:
        raise AnchorRefusedError(f"reviewed disposition has no anchored site: {sorted(missing)!r}")
    operations: list[PlannedOperation] = []
    for disposition in sorted(manifest.dispositions, key=lambda item: item.site_key):
        site = stream_by_id[disposition.site_key]
        if disposition.disposition == "rejected":
            raise AnchorRefusedError(
                f"reviewed disposition is not compilable: {disposition.disposition}"
            )
        if disposition.disposition == "query_transform":
            require_complete_receiver_physical_context(site)
        operations.append(
            PlannedOperation(
                disposition=disposition.disposition,
                reason=disposition.reason,
                consumed_site_ids=(site.original_site_id,),
                shape_key=site.shape_key,
            )
        )
    deferred = tuple(sorted(site.site_key for site in manifest.unclassified_sites))
    pending = tuple(sorted(set(stream_by_id) - reviewed_ids - set(deferred)))
    if (
        any(site.domain != "test_fixture" for site in manifest.unclassified_sites)
        or any(site_id not in stream_by_id for site_id in deferred)
        or reviewed_ids & set(deferred)
        or set(stream_by_id) != reviewed_ids | set(deferred) | set(pending)
    ):
        raise AnchorRefusedError("deferred fixture ledger does not match anchored stream")
    disposition_counts = tuple(sorted(Counter(item.disposition for item in operations).items()))
    shape_group_counts = tuple(sorted(Counter(item.shape_key for item in operations).items()))
    if (
        dict(disposition_counts).get("query_transform") != 201
        or dict(disposition_counts).get("approved_core") != 80
    ):
        raise AnchorRefusedError("reviewed disposition checkpoint counts do not match")
    return DispositionPlan(
        operations=tuple(operations),
        reviewed_deferred_site_ids=deferred,
        generated_fixture_operations=(),
        pending_site_ids=pending,
        disposition_counts=disposition_counts,
        shape_group_counts=shape_group_counts,
        rule_family_counts=(),
        symbol_origin_counts=(),
        generated_fixture_family_counts=(),
    )


def _neutral_rule(site: MigrationSite) -> tuple[str, str] | None:
    """Return one finite structural rule and its proven origin, or fail closed."""
    anchor = site.anchor
    context = anchor.context
    if (
        site.diagnostic_code is DiagnosticCode.UNSUPPORTED_BINDING
        and context is not None
        and context.receiver_type_origin
        in {
            "orchestrator.graph.GraphProjection",
            "orchestrator.graph._commands.GraphProjection",
            "orchestrator.graph.projections.GraphProjection",
        }
    ):
        return "typed_projection_binding", context.receiver_type_origin
    if (
        site.diagnostic_code is DiagnosticCode.UNSUPPORTED_BINDING
        and context is not None
        and _is_projection_factory(context.callee_origin)
    ):
        return "typed_projector_binding", context.callee_origin
    if (
        context is not None
        and _is_projection_factory(context.callee_origin)
        and context.projection_role == "receiver"
    ):
        return "typed_projector_binding", context.callee_origin
    if context is not None and context.physical_access_kind is not None:
        return None
    if (
        context is not None
        and context.callee_origin in _DERIVED_VALUE_SINKS
        and context.projection_role == "derived_value"
    ):
        return "derived_value_sink", context.callee_origin
    if (
        context is not None
        and context.callee_origin in _PUBLIC_PROJECTION_CALLS
        and (
            context.projection_role == "keyword"
            and context.keyword_name == "projection"
            or context.projection_role == "positional"
            and context.positional_index
            in _PUBLIC_PROJECTION_ARGUMENT_POSITIONS.get(context.callee_origin, frozenset({0}))
        )
    ):
        return "public_graph_call", context.callee_origin
    if context is not None and _is_projection_factory(context.callee_origin):
        return "projector_fixture_flow", context.callee_origin
    return None


def _generated_fixture_rule(site: MigrationSite) -> GeneratedFixtureOperation | None:
    """Recognize only the approved physical mutation families from anchor facts."""
    context = site.anchor.context
    if (
        context is None
        or context.projection_role != "receiver"
        or context.physical_access_kind is None
        or context.physical_old_field_name is None
        or context.physical_operation_shape is None
    ):
        return None
    facts = (
        ("access_kind", context.physical_access_kind.value),
        ("field", context.physical_old_field_name),
        ("operation_shape", context.physical_operation_shape),
        ("parent_shape", site.parent_shape),
    )
    rule_id: str | None = None
    if (
        context.physical_access_kind is AccessKind.NESTED_ASSIGNMENT
        and site.operation_shape == "assignment"
    ):
        rule_id = "physical_nested_assignment"
    elif context.physical_access_kind in {
        AccessKind.DIRECT_ASSIGNMENT,
        AccessKind.LITERAL_SUBSCRIPT_READ,
    } and site.operation_shape in {
        "assignment",
        "update",
        "literal_field_update",
        "literal_field_mutation",
    }:
        rule_id = "literal_field_update_mutation"
    elif context.physical_access_kind is AccessKind.APPEND_EXTEND and site.operation_shape in {
        "append",
        "extend",
        "append_extend",
        "call",
    }:
        rule_id = "physical_append_extend"
    if rule_id is None:
        return None
    return GeneratedFixtureOperation(
        site_id=site.original_site_id,
        rule_id=rule_id,
        shape_key=site.shape_key,
        evidence=facts,
    )


def _approved_core_rule(site: MigrationSite) -> bool:
    """Prove a reviewed core site is one allowlisted physical projection read."""
    context = site.anchor.context
    return (
        site.relative_path in _APPROVED_CORE_PATHS
        and context is not None
        and context.projection_role == "receiver"
        and context.receiver_type_origin in _GRAPH_PROJECTION_ORIGINS
        and context.physical_access_kind is not None
        and context.physical_operation_shape == context.physical_access_kind.value
        and context.physical_operation_shape in _APPROVED_CORE_READ_SHAPES
        and site.parent_shape not in {"assignment", "deletion", "mutation"}
    )


def plan_structural_dispositions(
    stream: OperationStream, manifest: QueryMigrationManifest
) -> DispositionPlan:
    """Close unchanged dispositions through imported-origin and CST argument evidence."""
    initial = plan_reviewed_dispositions(stream, manifest)
    by_id = {site.original_site_id: site for site in stream.sites}
    operations: list[PlannedOperation] = []
    rule_operations: list[StructuralRuleOperation] = []
    generated_fixture_operations: list[GeneratedFixtureOperation] = []

    for operation in initial.operations:
        site_id = operation.consumed_site_ids[0]
        site = by_id[site_id]
        if operation.disposition == "approved_core":
            if not _approved_core_rule(site):
                raise AnchorRefusedError(
                    "approved core is not an allowlisted physical storage operation"
                )
            operations.append(operation)
            continue
        if operation.disposition != "projection_neutral":
            operations.append(operation)
            continue
        rule = _neutral_rule(site)
        if rule is None:
            raise AnchorRefusedError(
                f"reviewed projection-neutral site has no structural rule: {site_id}"
            )
        family, origin = rule
        operations.append(operation.model_copy(update={"reason": f"structural:{family}:{origin}"}))
        rule_operations.append(
            StructuralRuleOperation(
                site_id=site_id, rule_id=family, origin=origin, shape_key=site.shape_key
            )
        )

    for site_id in initial.pending_site_ids:
        site = by_id[site_id]
        rule = _neutral_rule(site)
        if rule is None:
            fixture_operation = _generated_fixture_rule(site)
            if fixture_operation is None:
                raise AnchorRefusedError(
                    "pending site has no finite neutral or generated fixture rule: "
                    f"{site_id}:{site.shape_key}"
                )
            generated_fixture_operations.append(fixture_operation)
            continue
        family, origin = rule
        operations.append(
            PlannedOperation(
                disposition="projection_neutral",
                reason=f"structural:{family}:{origin}",
                consumed_site_ids=(site_id,),
                shape_key=site.shape_key,
            )
        )
        rule_operations.append(
            StructuralRuleOperation(
                site_id=site_id, rule_id=family, origin=origin, shape_key=site.shape_key
            )
        )

    operations.sort(key=lambda operation: operation.consumed_site_ids)
    generated_fixture_operations.sort(key=lambda item: item.site_id)
    disposition_counts = tuple(sorted(Counter(item.disposition for item in operations).items()))
    shape_group_counts = tuple(sorted(Counter(item.shape_key for item in operations).items()))
    rule_family_counts = tuple(sorted(Counter(item.rule_id for item in rule_operations).items()))
    symbol_origin_counts = tuple(sorted(Counter(item.origin for item in rule_operations).items()))
    generated_fixture_family_counts = tuple(
        sorted(Counter(item.rule_id for item in generated_fixture_operations).items())
    )
    if (
        len(operations)
        + len(initial.reviewed_deferred_site_ids)
        + len(generated_fixture_operations)
        != 803
    ):
        raise AnchorRefusedError(
            "structural disposition partition does not match the approved counts"
        )
    return DispositionPlan(
        operations=tuple(operations),
        reviewed_deferred_site_ids=initial.reviewed_deferred_site_ids,
        generated_fixture_operations=tuple(generated_fixture_operations),
        pending_site_ids=(),
        disposition_counts=disposition_counts,
        shape_group_counts=shape_group_counts,
        neutral_rule_operations=tuple(sorted(rule_operations, key=lambda item: item.site_id)),
        rule_family_counts=rule_family_counts,
        symbol_origin_counts=symbol_origin_counts,
        generated_fixture_family_counts=generated_fixture_family_counts,
    )


def _refuse_unknown_shape(node: cst.CSTNode) -> AnchorRefusedError:
    return AnchorRefusedError(f"unknown structural shape: {type(node).__name__}")


def _normalized_node(node: cst.CSTNode) -> str | None:
    try:
        return ast.unparse(ast.parse(cst.Module([]).code_for_node(node)))
    except SyntaxError:
        return None


def _qualified_functions(module: cst.Module) -> dict[int, str]:
    names: dict[int, str] = {}

    class Visitor(cst.CSTVisitor):
        def __init__(self) -> None:
            self.stack: list[str] = []

        def on_visit(self, node: cst.CSTNode) -> bool:
            names[id(node)] = ".".join(self.stack) or "<module>"
            if isinstance(node, (cst.FunctionDef, cst.ClassDef)):
                self.stack.append(node.name.value)
            return True

        def on_leave(self, original_node: cst.CSTNode) -> None:
            if isinstance(original_node, (cst.FunctionDef, cst.ClassDef)):
                self.stack.pop()

    module.visit(Visitor())
    return names


def _transparent_parent(node: cst.CSTNode, parents: dict[cst.CSTNode, cst.CSTNode]) -> cst.CSTNode:
    parent = parents[node]
    while isinstance(parent, (cst.Expr, cst.SimpleStatementLine, cst.ParenthesizedWhitespace)):
        parent = parents[parent]
    return parent


def _parent_shape(node: cst.CSTNode, parents: dict[cst.CSTNode, cst.CSTNode]) -> str:
    if isinstance(node, cst.Del):
        return "deletion"
    parent = parents[node]
    if isinstance(parent, (cst.Expr, cst.SimpleStatementLine)):
        return "bare_expression"
    parent = _transparent_parent(node, parents)
    if isinstance(parent, cst.Return):
        return "return"
    if isinstance(parent, cst.AssignTarget):
        return "assignment_target"
    if isinstance(parent, (cst.Assign, cst.AnnAssign, cst.AugAssign)):
        return "assignment_value"
    if isinstance(parent, cst.Del):
        return "deletion"
    if isinstance(parent, (cst.For, cst.CompFor)):
        return "iterable"
    if isinstance(parent, (cst.If, cst.While, cst.Assert)):
        return "condition"
    if isinstance(parent, (cst.Comparison, cst.ComparisonTarget)):
        return "comparison_membership"
    if isinstance(parent, cst.Arg):
        return "call_argument"
    if isinstance(parent, cst.Call):
        return "call_receiver"
    if isinstance(parent, cst.Attribute):
        return "attribute_receiver"
    if isinstance(parent, cst.Subscript):
        return "nested_receiver"
    if isinstance(parent, (cst.DictElement, cst.DictComp)):
        return "dict_element"
    if isinstance(parent, cst.Annotation):
        return "annotation"
    if isinstance(parent, cst.Parameters):
        return "typed_parameter"
    if isinstance(parent, (cst.BooleanOperation, cst.IfExp, cst.UnaryOperation)):
        return "boolean_expression"
    if isinstance(parent, (cst.Tuple, cst.List, cst.Set, cst.Element)):
        return "collection_element"
    if isinstance(parent, (cst.Await, cst.Yield)):
        return "yield_await"
    raise _refuse_unknown_shape(parent)


def _operation_shape(node: cst.CSTNode, access_kind: AccessKind | None) -> str:
    if access_kind is not None:
        if access_kind is AccessKind.MEMBERSHIP:
            return "membership"
        if access_kind in {AccessKind.ITEMS, AccessKind.VALUES, AccessKind.KEYS}:
            return f"{access_kind.value}_iteration"
        if access_kind in {AccessKind.DIRECT_ASSIGNMENT, AccessKind.NESTED_ASSIGNMENT}:
            return "assignment"
        if access_kind is AccessKind.APPEND_EXTEND:
            return "append_extend"
        if access_kind is AccessKind.DELETE_POP:
            return "deletion"
        if access_kind is AccessKind.FIXTURE_CONSTRUCTION:
            return "fixture_construction"
        if access_kind is AccessKind.UNTYPED_ESCAPE:
            return "typed_pass_through"
        if access_kind is AccessKind.GET:
            return "map_get"
        if access_kind is AccessKind.LITERAL_SUBSCRIPT_READ:
            return "subscript_read"
        return access_kind.value
    if isinstance(node, cst.Call):
        return "call"
    if isinstance(node, cst.Comparison):
        return "comparison"
    raise _refuse_unknown_shape(node)


def _diagnostic_operation_shape(node: cst.CSTNode, code: DiagnosticCode) -> str:
    if isinstance(node, cst.Call):
        if isinstance(node.func, cst.Attribute):
            if node.func.attr.value == "get" and isinstance(node.func.value, cst.Subscript):
                return "nested_get"
            if node.func.attr.value in {
                "items",
                "values",
                "keys",
                "update",
                "append",
                "extend",
                "pop",
                "setdefault",
            }:
                return node.func.attr.value
        return "call"
    if isinstance(node, cst.Comparison):
        return "comparison"
    if isinstance(node, cst.Del):
        return "deletion"
    if isinstance(node, cst.Subscript):
        return "subscript"
    if isinstance(
        node, (cst.Param, cst.Name, cst.AnnAssign, cst.Assign, cst.FunctionDef, cst.Return)
    ):
        return "typed_pass_through"
    raise AnchorRefusedError(f"unknown diagnostic operation: {code.value}:{type(node).__name__}")


def _node_candidates(
    module: cst.Module,
) -> tuple[
    dict[tuple[str, str], list[cst.CSTNode]],
    dict[cst.CSTNode, cst.CSTNode],
    dict[cst.CSTNode, object],
    dict[int, str],
    dict[cst.CSTNode, object],
]:
    wrapper = MetadataWrapper(module)
    metadata = wrapper.resolve_many((ParentNodeProvider, PositionProvider))
    parents = metadata[ParentNodeProvider]
    positions = metadata[PositionProvider]
    qualified = _qualified_functions(wrapper.module)
    candidates: dict[tuple[str, str], list[cst.CSTNode]] = defaultdict(list)

    class Visitor(cst.CSTVisitor):
        def on_visit(self, node: cst.CSTNode) -> bool:
            if not isinstance(node, (cst.BaseExpression, cst.Del)):
                return True
            expression = _normalized_node(node)
            if expression is not None:
                candidates[(qualified[id(node)], expression)].append(node)
            return True

    wrapper.visit(Visitor())
    for nodes in candidates.values():
        nodes.sort(key=lambda node: (positions[node].start.line, positions[node].start.column))
    return (
        candidates,
        parents,
        positions,
        qualified,
        wrapper.resolve(QualifiedNameProvider),
    )


def _source_map(sources: Iterable[SourceSnapshot]) -> dict[str, SourceSnapshot]:
    snapshots = tuple(sources)
    result = {source.relative_path: source for source in snapshots}
    if len(result) != len(snapshots):
        raise AnchorRefusedError("source snapshots contain duplicate paths")
    return result


def _expected_digest_map(inventory: AccessInventory) -> dict[str, str]:
    return {item.relative_path: item.digest for item in inventory.source_digests}


def _skeleton_sites(skeleton: QueryMigrationManifest) -> dict[str, object]:
    return {site.site_key: site for site in (*skeleton.dispositions, *skeleton.unclassified_sites)}


def _matches_access_kind(
    node: cst.CSTNode,
    kind: AccessKind,
    parents: dict[cst.CSTNode, cst.CSTNode],
) -> bool:
    signature = _physical_signature(node, parents)
    if signature is not None:
        return signature[2] is kind
    parent = parents[node]
    if kind is AccessKind.DIRECT_ITERATION:
        return isinstance(parent, (cst.For, cst.CompFor))
    if kind in {AccessKind.FIXTURE_CONSTRUCTION, AccessKind.UNPACK_CAST}:
        return isinstance(node, cst.Call)
    if kind is AccessKind.UNTYPED_ESCAPE:
        return isinstance(node, cst.BaseExpression)
    return False


def _scope_lines(
    module: cst.Module,
    positions: dict[cst.CSTNode, object],
    qualified: dict[int, str],
) -> dict[int, str]:
    ranges = [
        (
            position.start.line,
            position.end.line,
            ".".join(part for part in (qualified[id(node)], node.name.value) if part != "<module>")
            or node.name.value,
        )
        for node, position in positions.items()
        if isinstance(node, cst.FunctionDef)
    ]
    return {
        line: max(
            (item for item in ranges if item[0] <= line <= item[1]),
            key=lambda item: item[0],
            default=(0, 0, "<module>"),
        )[2]
        for line in range(1, len(module.code.splitlines()) + 1)
    }


def _matching_occurrence_nodes(
    *,
    candidates: dict[tuple[str, str], list[cst.CSTNode]],
    parents: dict[cst.CSTNode, cst.CSTNode],
    qualified_function: str,
    normalized_expression: str,
    access_kinds: tuple[AccessKind, ...],
) -> tuple[cst.CSTNode, ...]:
    """Return the exact candidate set used by every occurrence anchor consumer."""
    nodes = tuple(
        node
        for node in candidates.get((qualified_function, normalized_expression), ())
        if any(_matches_access_kind(node, kind, parents) for kind in access_kinds)
    )
    if not access_kinds or len(nodes) != len(access_kinds):
        raise AnchorRefusedError("ambiguous occurrence anchor")
    return nodes


def _matching_diagnostic_nodes(
    *,
    source: str,
    module: cst.Module,
    positions: dict[cst.CSTNode, object],
    scope_lines: dict[int, str],
    qualified_function: str,
    code: DiagnosticCode,
    normalized_source_pattern: str,
    signatures: tuple[tuple[str, str], ...],
) -> tuple[cst.CSTNode, ...]:
    """Return the exact candidate set used by every diagnostic anchor consumer."""
    matching_lines = {
        index + 1
        for index, line in enumerate(source.splitlines())
        if " ".join(line.strip().split()) == normalized_source_pattern
        and scope_lines.get(index + 1) == qualified_function
    }
    signature_counts = Counter(signatures)
    nodes_by_signature: dict[tuple[str, str], tuple[cst.CSTNode, ...]] = {}
    for signature, expected_count in signature_counts.items():
        nodes = tuple(
            node
            for node, position in positions.items()
            if position.start.line in matching_lines
            and type(node).__name__ == signature[0]
            and (_normalized_node(node) or module.code_for_node(node).strip()) == signature[1]
        )
        if len(nodes) != expected_count:
            raise AnchorRefusedError(f"ambiguous {code.value} diagnostic anchor")
        nodes_by_signature[signature] = nodes
    return tuple(
        sorted(
            (candidate for values in nodes_by_signature.values() for candidate in values),
            key=lambda candidate: (
                positions[candidate].start.line,
                positions[candidate].start.column,
                type(candidate).__name__,
            ),
        )
    )


def _diagnostic_node(
    nodes: list[cst.CSTNode], source_node_type: str, normalized_cst_expression: str
) -> cst.CSTNode:
    matching = [
        node
        for node in nodes
        if type(node).__name__ == source_node_type
        and (_normalized_node(node) or cst.Module([]).code_for_node(node).strip())
        == normalized_cst_expression
    ]
    if len(matching) != 1:
        raise AnchorRefusedError("ambiguous diagnostic CST anchor")
    return matching[0]


def _anchor_evidence(
    node: cst.CSTNode,
    *,
    normalized_expression: str,
    ordinal: int,
    stored_context: ProjectionCallContext | None,
    qualified_names: dict[cst.CSTNode, object],
    parents: dict[cst.CSTNode, cst.CSTNode],
    expected_access_kind: AccessKind | None = None,
) -> CstAnchorEvidence:
    return CstAnchorEvidence(
        node_type=type(node).__name__,
        normalized_expression=normalized_expression,
        same_expression_ordinal=ordinal,
        context=_reanchor_context(
            node, stored_context, qualified_names, parents, expected_access_kind
        ),
    )


def compile_operation_stream(
    sources: Iterable[SourceSnapshot],
    inventory: AccessInventory,
    skeleton: QueryMigrationManifest,
) -> OperationStream:
    """Anchor every authoritative occurrence and diagnostic exactly once in source snapshots."""
    if skeleton.baseline_revision != inventory.baseline_revision:
        raise AnchorRefusedError("inventory and skeleton baseline revisions differ")
    snapshots = _source_map(sources)
    expected_digests = _expected_digest_map(inventory)
    if not expected_digests:
        raise AnchorRefusedError("inventory has no source digests")
    for relative_path, expected_digest in expected_digests.items():
        source = snapshots.get(relative_path)
        if source is None:
            raise AnchorRefusedError(f"missing source snapshot: {relative_path}")
        if source_digest(source.source) != expected_digest:
            raise AnchorRefusedError(f"digest mismatch: {relative_path}")

    skeleton_by_id = _skeleton_sites(skeleton)
    diagnostics_by_path: dict[str, list[object]] = defaultdict(list)
    diagnostics_by_path_raw: dict[str, list[object]] = defaultdict(list)
    for diagnostic in inventory.diagnostics:
        diagnostics_by_path_raw[diagnostic.relative_path].append(diagnostic)
    for relative_path, diagnostics in diagnostics_by_path_raw.items():
        diagnostics_by_path[relative_path].extend(diagnostics)

    sites: list[MigrationSite] = []
    occurrences_by_path: dict[str, list[object]] = defaultdict(list)
    for occurrence in inventory.occurrences:
        occurrences_by_path[occurrence.relative_path].append(occurrence)
    for relative_path in sorted({*occurrences_by_path, *diagnostics_by_path}):
        snapshot = snapshots.get(relative_path)
        if snapshot is None:
            raise AnchorRefusedError(f"missing source snapshot: {relative_path}")
        module = cst.parse_module(snapshot.source)
        candidates, parents, positions, qualified, qualified_names = _node_candidates(module)
        scope_lines = _scope_lines(module, positions, qualified)
        for occurrence in occurrences_by_path[relative_path]:
            matching_occurrences = tuple(
                item
                for item in occurrences_by_path[relative_path]
                if item.qualified_function == occurrence.qualified_function
                and item.normalized_expression == occurrence.normalized_expression
            )
            nodes = _matching_occurrence_nodes(
                candidates=candidates,
                parents=parents,
                qualified_function=occurrence.qualified_function,
                normalized_expression=occurrence.normalized_expression,
                access_kinds=tuple(item.kind for item in matching_occurrences),
            )
            identities = {
                occurrence_id(
                    inventory.baseline_revision,
                    relative_path,
                    occurrence.qualified_function,
                    occurrence.normalized_expression,
                    ordinal,
                ): node
                for ordinal, node in enumerate(nodes)
            }
            if occurrence.occurrence_id not in identities:
                raise AnchorRefusedError(f"identity mismatch: {occurrence.occurrence_id}")
            node = identities[occurrence.occurrence_id]
            skeleton_site = skeleton_by_id.get(occurrence.occurrence_id)
            if skeleton_site is None or skeleton_site.site_key != occurrence.occurrence_id:
                raise AnchorRefusedError(
                    f"missing occurrence skeleton identity: {occurrence.occurrence_id}"
                )
            position = positions[node].start
            if _normalized_node(node) != occurrence.normalized_expression:
                raise AnchorRefusedError(f"identity mismatch: {occurrence.occurrence_id}")
            sites.append(
                MigrationSite(
                    origin="occurrence",
                    original_site_id=occurrence.occurrence_id,
                    relative_path=relative_path,
                    qualified_function=occurrence.qualified_function,
                    access_kind=occurrence.kind,
                    old_field_name=occurrence.old_field_name,
                    diagnostic_code=None,
                    normalized_expression=occurrence.normalized_expression,
                    ordinal=next(
                        ordinal for ordinal, candidate in enumerate(nodes) if candidate is node
                    ),
                    source_digest=source_digest(snapshot.source),
                    locator=SourceLocator(line=position.line, column=position.column),
                    anchor=_anchor_evidence(
                        node,
                        normalized_expression=occurrence.normalized_expression,
                        ordinal=next(
                            ordinal for ordinal, candidate in enumerate(nodes) if candidate is node
                        ),
                        stored_context=occurrence.context,
                        qualified_names=qualified_names,
                        parents=parents,
                        expected_access_kind=occurrence.kind,
                    ),
                    parent_shape=_parent_shape(node, parents),
                    operation_shape=_operation_shape(node, occurrence.kind),
                )
            )
        for diagnostic in diagnostics_by_path[relative_path]:
            pattern = diagnostic.normalized_source_pattern
            group = [
                item
                for item in diagnostics_by_path[relative_path]
                if item.qualified_function == diagnostic.qualified_function
                and item.code is diagnostic.code
                and item.normalized_source_pattern == pattern
            ]
            signature = (diagnostic.source_node_type, diagnostic.normalized_cst_expression)
            all_nodes = _matching_diagnostic_nodes(
                source=snapshot.source,
                module=module,
                positions=positions,
                scope_lines=scope_lines,
                qualified_function=diagnostic.qualified_function,
                code=diagnostic.code,
                normalized_source_pattern=pattern,
                signatures=tuple(
                    (item.source_node_type, item.normalized_cst_expression) for item in group
                ),
            )
            if diagnostic.same_pattern_ordinal >= len(all_nodes):
                raise AnchorRefusedError("missing diagnostic CST anchor")
            ordinal = diagnostic.same_pattern_ordinal
            node = all_nodes[ordinal]
            if (
                type(node).__name__ != signature[0]
                or (_normalized_node(node) or cst.Module([]).code_for_node(node).strip())
                != signature[1]
            ):
                raise AnchorRefusedError("diagnostic identity mismatch")
            diagnostic_key = disposition_site_key(
                baseline_revision=inventory.baseline_revision,
                relative_path=relative_path,
                qualified_function=diagnostic.qualified_function,
                normalized_source_pattern=pattern,
                diagnostic_code=diagnostic.code,
                same_pattern_ordinal=ordinal,
            )
            skeleton_site = skeleton_by_id.get(diagnostic_key)
            if skeleton_site is None or skeleton_site.site_key != diagnostic_key:
                raise AnchorRefusedError("missing diagnostic skeleton identity")
            line = positions[node].start.line
            nodes = [node]
            if len(nodes) != 1:
                raise AnchorRefusedError("ambiguous diagnostic CST anchor")
            node = _diagnostic_node(
                nodes, diagnostic.source_node_type, diagnostic.normalized_cst_expression
            )
            sites.append(
                MigrationSite(
                    origin="diagnostic",
                    original_site_id=diagnostic_key,
                    relative_path=relative_path,
                    qualified_function=diagnostic.qualified_function,
                    access_kind=None,
                    old_field_name=None,
                    diagnostic_code=diagnostic.code,
                    normalized_expression=pattern,
                    ordinal=ordinal,
                    source_digest=source_digest(snapshot.source),
                    locator=SourceLocator(line=line, column=diagnostic.column),
                    anchor=_anchor_evidence(
                        node,
                        normalized_expression=(
                            _normalized_node(node) or cst.Module([]).code_for_node(node).strip()
                        ),
                        ordinal=ordinal,
                        stored_context=diagnostic.context,
                        qualified_names=qualified_names,
                        parents=parents,
                    ),
                    parent_shape=_parent_shape(node, parents),
                    operation_shape=_diagnostic_operation_shape(node, diagnostic.code),
                )
            )
    expected_ids = {item.occurrence_id for item in inventory.occurrences} | {
        item.site_key for item in skeleton_by_id.values() if item.diagnostic_code is not None
    }
    actual_ids = {site.original_site_id for site in sites}
    if actual_ids != expected_ids or len(sites) != len(expected_ids):
        raise AnchorRefusedError(
            "operation stream does not adapt every inventory site exactly once"
        )
    result = OperationStream(
        sites=tuple(
            sorted(
                sites,
                key=lambda site: (
                    site.relative_path,
                    site.locator.line,
                    site.locator.column,
                    site.original_site_id,
                ),
            )
        )
    )
    return result


def shape_summary(stream: OperationStream) -> dict[str, int]:
    """Return deterministic structural grouping counts without site or source policy."""
    return dict(sorted(Counter(site.shape_key for site in stream.sites).items()))
