"""Workflow event types and emitters."""

from orchestrator.workflow.events.types import (
    AgentChangedEvent,
    AgentDiedEvent,
    AgentErrorEvent,
    AgentFixCompleted,
    AgentFixStarted,
    AgentOutputEvent,
    ApprovalDecision,
    ApprovalRequested,
    AttemptUpdated,
    AutoVerifyCompleted,
    BackMergeCompleted,
    BackMergeReverted,
    BufferingEmitter,
    ChildCompleted,
    ChildFailed,
    ChildSpawned,
    ChecklistGateEvaluated,
    ChecklistItemGraded,
    ChecklistItemUpdated,
    ClarificationRequested,
    ClarificationResponded,
    ConflictResolved,
    FanOutChildrenCreated,
    FanOutChildrenReset,
    FanOutChildRetried,
    FanOutCompleted,
    FanOutSpawned,
    GradeDetail,
    GradesEvaluated,
    HealthCheckEvent,
    ParentOversightFactsUpdated,
    PruneApplied,
    RunCreated,
    RunDeleted,
    RunMetadataUpdated,
    RunStatusChanged,
    RunStepBackward,
    RunWorktreeCommitCompleted,
    RunWorktreeCommitFailed,
    RunWorktreeCommitRequested,
    RunWorktreeCreationFailed,
    RunWorktreeCreationRequested,
    RunWorktreeResetCompleted,
    RunWorktreeResetFailed,
    RunWorktreeResetRequested,
    RunWorktreeUpdated,
    SignalEnqueued,
    SignalProcessed,
    StepCompleted,
    StepCreated,
    StepHumanApprovalRecorded,
    StepIndexRewound,
    StepSkipped,
    TaskAttemptCreated,
    TaskCreated,
    TaskReverted,
    TaskStatusChanged,
    TestRunCompleted,
    TestRunStarted,
    WorkflowEvent,
)
from orchestrator.workflow.events.logger import PersistentEventEmitter

_EVENT_TYPE_MAP: dict[str, type[WorkflowEvent]] = {
    "run_status_changed": RunStatusChanged,
    "task_status_changed": TaskStatusChanged,
    "checklist_gate_evaluated": ChecklistGateEvaluated,
    "checklist_item_graded": ChecklistItemGraded,
    "checklist_item_updated": ChecklistItemUpdated,
    "grades_evaluated": GradesEvaluated,
    "auto_verify_completed": AutoVerifyCompleted,
    "step_completed": StepCompleted,
    "step_skipped": StepSkipped,
    "step_human_approval_recorded": StepHumanApprovalRecorded,
    "run_step_backward": RunStepBackward,
    "run_worktree_commit_requested": RunWorktreeCommitRequested,
    "run_worktree_commit_completed": RunWorktreeCommitCompleted,
    "run_worktree_commit_failed": RunWorktreeCommitFailed,
    "agent_changed": AgentChangedEvent,
    "agent_changed_event": AgentChangedEvent,
    "agent_died_event": AgentDiedEvent,
    "task_reverted": TaskReverted,
    "health_check": HealthCheckEvent,
    "health_check_event": HealthCheckEvent,
    "agent_output": AgentOutputEvent,
    "agent_output_event": AgentOutputEvent,
    "agent_error": AgentErrorEvent,
    "agent_error_event": AgentErrorEvent,
    "clarification_requested": ClarificationRequested,
    "clarification_responded": ClarificationResponded,
    "approval_requested": ApprovalRequested,
    "approval_decision": ApprovalDecision,
    "prune_applied": PruneApplied,
    "test_run_started": TestRunStarted,
    "test_run_completed": TestRunCompleted,
    "conflict_resolved": ConflictResolved,
    "back_merge_completed": BackMergeCompleted,
    "back_merge_reverted": BackMergeReverted,
    "agent_fix_started": AgentFixStarted,
    "agent_fix_completed": AgentFixCompleted,
    "fan_out_spawned": FanOutSpawned,
    "child_spawned": ChildSpawned,
    "child_completed": ChildCompleted,
    "child_failed": ChildFailed,
    "fan_out_completed": FanOutCompleted,
    "run_created": RunCreated,
    "run_deleted": RunDeleted,
    "run_metadata_updated": RunMetadataUpdated,
    "step_created": StepCreated,
    "run_worktree_creation_requested": RunWorktreeCreationRequested,
    "run_worktree_creation_failed": RunWorktreeCreationFailed,
    "run_worktree_reset_requested": RunWorktreeResetRequested,
    "run_worktree_reset_completed": RunWorktreeResetCompleted,
    "run_worktree_reset_failed": RunWorktreeResetFailed,
    "run_worktree_updated": RunWorktreeUpdated,
    "task_created": TaskCreated,
    "task_attempt_created": TaskAttemptCreated,
    "attempt_updated": AttemptUpdated,
    "parent_oversight_facts_updated": ParentOversightFactsUpdated,
    "fan_out_children_created": FanOutChildrenCreated,
    "fan_out_children_reset": FanOutChildrenReset,
    "fan_out_child_retried": FanOutChildRetried,
    "step_index_rewound": StepIndexRewound,
    "signal_enqueued": SignalEnqueued,
    "signal_processed": SignalProcessed,
}


def deserialize_event(event_type: str, payload: str) -> WorkflowEvent:
    """Deserialize a stored event payload back to a WorkflowEvent object.

    Raises ValueError for unknown event_type strings.
    """
    cls = _EVENT_TYPE_MAP.get(event_type)
    if cls is None:
        raise ValueError(f"Unknown event type: {event_type!r}")
    return cls.model_validate_json(payload)


__all__ = [
    "AgentChangedEvent",
    "AgentDiedEvent",
    "AgentErrorEvent",
    "AgentFixCompleted",
    "AgentFixStarted",
    "AgentOutputEvent",
    "ApprovalDecision",
    "ApprovalRequested",
    "AttemptUpdated",
    "AutoVerifyCompleted",
    "BackMergeCompleted",
    "BackMergeReverted",
    "BufferingEmitter",
    "ChildCompleted",
    "ChildFailed",
    "ChildSpawned",
    "ChecklistGateEvaluated",
    "ChecklistItemGraded",
    "ChecklistItemUpdated",
    "ClarificationRequested",
    "ClarificationResponded",
    "ConflictResolved",
    "deserialize_event",
    "FanOutChildrenCreated",
    "FanOutChildrenReset",
    "FanOutChildRetried",
    "FanOutCompleted",
    "FanOutSpawned",
    "GradeDetail",
    "GradesEvaluated",
    "HealthCheckEvent",
    "ParentOversightFactsUpdated",
    "PersistentEventEmitter",
    "PruneApplied",
    "RunCreated",
    "RunDeleted",
    "RunMetadataUpdated",
    "RunStatusChanged",
    "RunStepBackward",
    "RunWorktreeCommitCompleted",
    "RunWorktreeCommitFailed",
    "RunWorktreeCommitRequested",
    "RunWorktreeCreationFailed",
    "RunWorktreeCreationRequested",
    "RunWorktreeResetCompleted",
    "RunWorktreeResetFailed",
    "RunWorktreeResetRequested",
    "RunWorktreeUpdated",
    "SignalEnqueued",
    "SignalProcessed",
    "StepCompleted",
    "StepCreated",
    "StepHumanApprovalRecorded",
    "StepIndexRewound",
    "StepSkipped",
    "TaskAttemptCreated",
    "TaskCreated",
    "TaskReverted",
    "TaskStatusChanged",
    "TestRunCompleted",
    "TestRunStarted",
    "WorkflowEvent",
]
