"""Git integration for orchestrator."""

from orchestrator.git.diff import (
    Cache,
    CachedDiffOps,
    CommitInfo,
    DiffOps,
    DiffResult,
    DiffScope,
    FileStatus,
    GitDiffOps,
    LRUCache,
    ModifiedFile,
    get_branch_diff,
    get_commit_diff,
    get_commit_log,
    get_modified_files,
    get_task_diff,
)
from orchestrator.git.errors import (
    BranchError,
    BranchNotFoundError,
    BranchSafetyError,
    GitCommandError,
    GitError,
    MergeConflictError,
    WorktreeCommitError,
    WorktreeResetError,
    WorktreeError,
)
from orchestrator.git.ops import (
    BackMergeResult,
    BlockResolution,
    BranchStatus,
    FileSelectionEntry,
    Hunk,
    ParentChildMergeResult,
    PruneStats,
    RevertBackMergeResult,
    apply_prune,
    back_merge,
    compute_selection_preview,
    get_branch_status,
    get_conflict_blocks,
    get_conflict_files,
    merge_child_into_parent,
    merge_back,
    parse_conflict_blocks,
    preview_prune,
    prune_hunks,
    prune_lines,
    resolve_conflict,
    revert_back_merge,
    revert_file,
)
from orchestrator.git.ops.conflict_ops import (
    _apply_resolutions,  # pyright: ignore[reportPrivateUsage]
)
from orchestrator.git.ops.prune_ops import (
    _build_hunk_reverse_patch,  # pyright: ignore[reportPrivateUsage]
    _build_line_reverse_patch,  # pyright: ignore[reportPrivateUsage]
    _count_selected_hunk_lines,  # pyright: ignore[reportPrivateUsage]
    _count_selected_range_lines,  # pyright: ignore[reportPrivateUsage]
    _file_exists_at_ref,  # pyright: ignore[reportPrivateUsage]
    _parse_diff_sections,  # pyright: ignore[reportPrivateUsage]
    _parse_file_diff_hunks,  # pyright: ignore[reportPrivateUsage]
    _parse_hunk_header,  # pyright: ignore[reportPrivateUsage]
)
from orchestrator.git.project_init import InitializedProject, init_project
from orchestrator.git.repos import (
    BranchInfo,
    RepoInfo,
    RepoNotFoundError,
    branch_count,
    get_repo,
    list_branches,
    list_repos,
)
from orchestrator.git.snapshot import SnapshotResult, delete_snapshot_ref, restore, snapshot
from orchestrator.git.testing import TestRunResult, TestRunner, TestSummary
from orchestrator.git.utils import (
    GIT_ADD_TIMEOUT_SECONDS,
    GIT_COMMIT_TIMEOUT_SECONDS,
    GIT_QUICK_TIMEOUT_SECONDS,
    WorktreeCommitResult,
    WorktreeResetResult,
    commit_uncommitted_changes,
    commit_uncommitted_changes_or_raise,
    get_head_commit,
    reset_worktree_changes,
    reset_worktree_to_ref,
)
from orchestrator.git.contamination import (
    dirty_paths,
    find_leaked_paths,
    resolve_main_worktree,
)
from orchestrator.git.worktree import (
    WorktreeInfo,
    WorktreeManager,
    get_agent_cache_write_paths,
    get_worktree_git_write_paths,
)

__all__ = [
    "dirty_paths",
    "find_leaked_paths",
    "resolve_main_worktree",
    "_apply_resolutions",
    "_build_hunk_reverse_patch",
    "_build_line_reverse_patch",
    "_count_selected_hunk_lines",
    "_count_selected_range_lines",
    "_file_exists_at_ref",
    "_parse_diff_sections",
    "_parse_file_diff_hunks",
    "_parse_hunk_header",
    "BackMergeResult",
    "BlockResolution",
    "CachedDiffOps",
    "DiffOps",
    "BranchError",
    "BranchInfo",
    "BranchNotFoundError",
    "BranchSafetyError",
    "BranchStatus",
    "Cache",
    "CommitInfo",
    "DiffResult",
    "DiffScope",
    "FileStatus",
    "GitCommandError",
    "GitDiffOps",
    "GitError",
    "GIT_ADD_TIMEOUT_SECONDS",
    "GIT_COMMIT_TIMEOUT_SECONDS",
    "GIT_QUICK_TIMEOUT_SECONDS",
    "InitializedProject",
    "LRUCache",
    "MergeConflictError",
    "ModifiedFile",
    "ParentChildMergeResult",
    "RepoInfo",
    "RepoNotFoundError",
    "RevertBackMergeResult",
    "SnapshotResult",
    "TestRunResult",
    "TestRunner",
    "TestSummary",
    "WorktreeError",
    "WorktreeInfo",
    "WorktreeManager",
    "WorktreeCommitError",
    "WorktreeCommitResult",
    "WorktreeResetError",
    "WorktreeResetResult",
    "FileSelectionEntry",
    "Hunk",
    "PruneStats",
    "apply_prune",
    "back_merge",
    "branch_count",
    "commit_uncommitted_changes",
    "commit_uncommitted_changes_or_raise",
    "compute_selection_preview",
    "delete_snapshot_ref",
    "get_branch_diff",
    "get_branch_status",
    "get_commit_diff",
    "get_commit_log",
    "get_conflict_blocks",
    "get_conflict_files",
    "get_modified_files",
    "get_head_commit",
    "get_repo",
    "get_task_diff",
    "get_agent_cache_write_paths",
    "get_worktree_git_write_paths",
    "init_project",
    "list_branches",
    "list_repos",
    "merge_back",
    "merge_child_into_parent",
    "parse_conflict_blocks",
    "preview_prune",
    "prune_hunks",
    "prune_lines",
    "resolve_conflict",
    "revert_back_merge",
    "revert_file",
    "reset_worktree_changes",
    "reset_worktree_to_ref",
    "restore",
    "snapshot",
]
