"""Git integration for orchestrator."""

from orchestrator.git.diff import (
    Cache,
    CommitInfo,
    DiffResult,
    DiffScope,
    FileStatus,
    GitDiffOps,
    LRUCache,
    ModifiedFile,
    get_branch_diff,
    get_commit_diff,
    get_commit_log,
    get_modified_files,
    get_task_diff,
)
from orchestrator.git.errors import (
    BranchError,
    BranchNotFoundError,
    GitError,
    MergeConflictError,
    WorktreeError,
)
from orchestrator.git.ops import (
    BackMergeResult,
    BlockResolution,
    BranchStatus,
    FileSelectionEntry,
    Hunk,
    PruneStats,
    RevertBackMergeResult,
    apply_prune,
    back_merge,
    compute_selection_preview,
    get_branch_status,
    get_conflict_blocks,
    get_conflict_files,
    merge_back,
    preview_prune,
    prune_hunks,
    prune_lines,
    resolve_conflict,
    revert_back_merge,
    revert_file,
)
from orchestrator.git.project_init import InitializedProject, init_project
from orchestrator.git.repos import (
    BranchInfo,
    RepoInfo,
    RepoNotFoundError,
    branch_count,
    get_repo,
    list_branches,
    list_repos,
)
from orchestrator.git.testing import TestRunResult, TestRunner, TestSummary
from orchestrator.git.worktree import WorktreeInfo, WorktreeManager

__all__ = [
    "BackMergeResult",
    "BlockResolution",
    "BranchError",
    "BranchInfo",
    "BranchNotFoundError",
    "BranchStatus",
    "Cache",
    "CommitInfo",
    "DiffResult",
    "DiffScope",
    "FileStatus",
    "GitDiffOps",
    "GitError",
    "InitializedProject",
    "LRUCache",
    "MergeConflictError",
    "ModifiedFile",
    "RepoInfo",
    "RepoNotFoundError",
    "RevertBackMergeResult",
    "TestRunResult",
    "TestRunner",
    "TestSummary",
    "WorktreeError",
    "WorktreeInfo",
    "WorktreeManager",
    "FileSelectionEntry",
    "Hunk",
    "PruneStats",
    "apply_prune",
    "back_merge",
    "branch_count",
    "compute_selection_preview",
    "get_branch_diff",
    "get_branch_status",
    "get_commit_diff",
    "get_commit_log",
    "get_conflict_blocks",
    "get_conflict_files",
    "get_modified_files",
    "get_repo",
    "get_task_diff",
    "init_project",
    "list_branches",
    "list_repos",
    "merge_back",
    "preview_prune",
    "prune_hunks",
    "prune_lines",
    "resolve_conflict",
    "revert_back_merge",
    "revert_file",
]
