"""Workflow engine and orchestration - all public symbols exhaustively re-exported."""

from typing import TYPE_CHECKING, Any

from orchestrator.workflow.artifacts import Artifact, ArtifactRegistry
from orchestrator.workflow.engine import (
    Clock,
    ConditionEvalError,
    ConditionEvaluator,
    DEFAULT_GRADE_ORDER,
    DefaultClock,
    EventEmitter,
    GateBlockedError,
    GateResult,
    GradeResult,
    InvalidTransitionError,
    NoOpEmitter,
    Parser,
    StepOutcome,
    Token,
    Tokenizer,
    TokenType,
    TransitionResult,
    VALID_TRANSITIONS,
    WorkflowEngine,
    WorkflowError,
    check_run_completion,
    check_step_progression,
    evaluate_checklist_gate,
    evaluate_condition,
    evaluate_gate,
    evaluate_grades,
    evaluate_transition_conditions,
    grade_meets_threshold,
    is_step_complete,
    step_has_failure,
    transition_after_verification,
    transition_from_approval,
    transition_from_clarification,
    transition_to_building,
    transition_to_pending_approval,
    transition_to_pending_clarification,
    transition_force_accept,
    transition_to_recovering,
    transition_to_verifying,
)
from orchestrator.workflow.engine.transitions import (
    _build_step_outcomes,  # pyright: ignore[reportPrivateUsage]
    _create_repeat_step_copies,  # pyright: ignore[reportPrivateUsage]
    _find_step_config,  # pyright: ignore[reportPrivateUsage]
    _get_variable_value_for_repeat,  # pyright: ignore[reportPrivateUsage]
    _parse_repeat_for_expression,  # pyright: ignore[reportPrivateUsage]
)
from orchestrator.workflow.locks import (
    InMemoryLockManager,
    LockManager,
    LockTimeoutError,
    TaskLockedError,
)
from orchestrator.workflow.events import (
    AgentChangedEvent,
    AgentDiedEvent,
    AgentErrorEvent,
    AgentFixCompleted,
    AgentFixStarted,
    AgentOutputEvent,
    ApprovalDecision,
    ApprovalRequested,
    AttemptUpdated,
    AutoVerifyCompleted,
    BackMergeCompleted,
    BackMergeReverted,
    BufferingEmitter,
    ChildCompleted,
    ChildFailed,
    ChildSpawned,
    ChecklistGateEvaluated,
    ChecklistItemGraded,
    ChecklistItemUpdated,
    ClarificationRequested,
    ClarificationResponded,
    ConflictResolved,
    deserialize_event,
    FanOutChildrenCreated,
    FanOutChildrenReset,
    FanOutChildRetried,
    FanOutCompleted,
    FanOutSpawned,
    GradeDetail,
    GradesEvaluated,
    HealthCheckEvent,
    ParentOversightFactsUpdated,
    PersistentEventEmitter,
    PruneApplied,
    RunCreated,
    RunDeleted,
    RunMetadataUpdated,
    RunStatusChanged,
    RunStepBackward,
    RunWorktreeCommitCompleted,
    RunWorktreeCommitFailed,
    RunWorktreeCommitRequested,
    RunWorktreeCreationFailed,
    RunWorktreeCreationRequested,
    RunWorktreeResetCompleted,
    RunWorktreeResetFailed,
    RunWorktreeResetRequested,
    RunWorktreeUpdated,
    SignalEnqueued,
    SignalProcessed,
    StepCompleted,
    StepCreated,
    StepHumanApprovalRecorded,
    StepIndexRewound,
    StepSkipped,
    TaskAttemptCreated,
    TaskCreated,
    TaskReverted,
    TaskStatusChanged,
    TestRunCompleted,
    TestRunStarted,
    WorkflowEvent,
)
from orchestrator.workflow.commands import (
    CompleteRunWorktreeCommitCommand,
    CompleteRunWorktreeResetCommand,
    CreateFanOutChildrenCommand,
    CreateRunCommand,
    CreateTaskAttemptCommand,
    CreateTaskCommand,
    DeleteRunCommand,
    FailRunWorktreeCommitCommand,
    FailRunWorktreeResetCommand,
    FailRunWorktreeCreationCommand,
    InitialAttemptForRunCreate,
    InitialStepForRunCreate,
    InitialTaskForRunCreate,
    RecordClarificationRequestCommand,
    RecordStepHumanApprovalCommand,
    RecordTaskRevertedCommand,
    RequestRunWorktreeCommitCommand,
    RequestRunWorktreeCreationCommand,
    RequestRunWorktreeResetCommand,
    ResetFanOutChildrenCommand,
    RetryFanOutChildCommand,
    RewindStepIndexCommand,
    SetChecklistGradeCommand,
    UpdateChecklistItemCommand,
    UpdateLatestAttemptCommand,
    UpdateParentOversightFactsCommand,
    UpdateRunMetadataCommand,
    UpdateRunStatusCommand,
    UpdateRunWorktreeCommand,
    UpdateTaskStatusCommand,
    build_create_run_command,
    expand_run_snapshot_for_projection,
    handle_complete_run_worktree_commit,
    handle_complete_run_worktree_reset,
    handle_create_fan_out_children,
    handle_create_run,
    handle_create_task,
    handle_create_task_attempt,
    handle_delete_run,
    handle_fail_run_worktree_commit,
    handle_fail_run_worktree_creation,
    handle_fail_run_worktree_reset,
    handle_record_clarification_request,
    handle_record_step_human_approval,
    handle_record_task_reverted,
    handle_request_run_worktree_commit,
    handle_request_run_worktree_creation,
    handle_request_run_worktree_reset,
    handle_reset_fan_out_children,
    handle_retry_fan_out_child,
    handle_rewind_step_index,
    handle_set_checklist_grade,
    handle_update_checklist_item,
    handle_update_latest_attempt,
    handle_update_parent_oversight_facts,
    handle_update_run_metadata,
    handle_update_run_status,
    handle_update_run_worktree,
    handle_update_task_status,
)
from orchestrator.workflow.signals import (
    EventSignalTransport,
    ExecutorCallbacks,
    InMemorySignalTransport,
    LoopAction,
    NoTaskReason,
    PendingSignal,
    RunWorkflow,
    SignalConsumer,
    SignalForInactiveRunError,
    SignalQueue,
    SignalTransport,
    WorkflowSignal,
    build_registry,
    resolve_no_task_action,
    signal_handler,
)
from orchestrator.workflow.agent import (
    AutoVerifyResult,
    AutoVerifyRunner,
    BuilderPrompt,
    ClarificationAnswer,
    ClarificationQuestion,
    ClarificationRequest,
    ClarificationResponse,
    CompressedDecision,
    CompressedDecisions,
    ContextError,
    LocalAutoVerifyRunner,
    RecoveryPrompt,
    SummaryCache,
    TaskContextBuilder,
    VerifierPrompt,
    build_artifact_header,
    compress_clarifications,
    count_tokens,
    decisions_from_config,
    derive_output_path,
    evaluate_auto_verify,
    extract_section,
    format_clarification_artifact,
    run_auto_verify,
    generate_builder_prompt,
    generate_recovery_prompt,
    generate_verifier_prompt,
    get_task_context,
    has_crashes,
    resolve_artifact_path,
    resolve_template,
    resolve_variables,
    truncate_to_tokens,
)

if TYPE_CHECKING:
    from orchestrator.workflow.graph_driver import GraphRunDriver, GraphRunOutcome
    from orchestrator.workflow.service import WorkflowService, find_step_config, find_task_config
from orchestrator.workflow.completion import handle_run_completion
from orchestrator.workflow.dry_run import (
    DryRunResult,
    build_dry_run_context,
    build_dry_run_prompt,
    execute_dry_run,
    get_step_by_id,
    parse_dry_run_response,
)
from orchestrator.workflow.delegation import (
    DelegateCommand,
    DelegateCommandKind,
    DelegateResultEnvelope,
    DelegatedWork,
    DelegatedWorkStatus,
    DelegationDecision,
    DelegationDecisionKind,
    DelegationPolicy,
    DelegationRecord,
    DelegationResultRecord,
    DelegationReviewStateRecord,
    DelegationRecorder,
    DelegationStableState,
    DelegationState,
    FanOutDelegationPolicy,
    FanOutFacts,
    apply_delegate_command,
    build_fan_out_facts,
    work_from_fan_out_child,
)
from orchestrator.workflow.legacy_run_facts import (
    APPEND_ONLY_OVERSIGHT_LIST_KEYS,
    DURABLE_PARENT_OVERSIGHT_FACT_KEYS,
    SET_UNION_OVERSIGHT_LIST_KEYS,
    durable_parent_oversight_patch,
)
from orchestrator.workflow.merge_readiness import (
    Gate,
    MergeReadiness,
    evaluate_merge_readiness_gates,
)

__all__ = [
    # Artifacts
    "Artifact",
    "ArtifactRegistry",
    # Engine (errors, gates, grades, transitions, condition evaluation)
    "_build_step_outcomes",
    "_create_repeat_step_copies",
    "_find_step_config",
    "_get_variable_value_for_repeat",
    "_parse_repeat_for_expression",
    "Clock",
    "ConditionEvalError",
    "ConditionEvaluator",
    "DEFAULT_GRADE_ORDER",
    "DefaultClock",
    "EventEmitter",
    "Gate",
    "GateBlockedError",
    "GateResult",
    "GradeResult",
    "InvalidTransitionError",
    "NoOpEmitter",
    "Parser",
    "StepOutcome",
    "Token",
    "Tokenizer",
    "TokenType",
    "TransitionResult",
    "VALID_TRANSITIONS",
    "WorkflowEngine",
    "WorkflowError",
    "check_run_completion",
    "check_step_progression",
    "evaluate_checklist_gate",
    "evaluate_condition",
    "evaluate_gate",
    "evaluate_grades",
    "evaluate_merge_readiness_gates",
    "evaluate_transition_conditions",
    "grade_meets_threshold",
    "is_step_complete",
    "step_has_failure",
    "transition_after_verification",
    "transition_from_approval",
    "transition_from_clarification",
    "transition_to_building",
    "transition_to_pending_approval",
    "transition_to_pending_clarification",
    "transition_force_accept",
    "transition_to_recovering",
    "transition_to_verifying",
    # Locks
    "InMemoryLockManager",
    "LockManager",
    "LockTimeoutError",
    "MergeReadiness",
    "TaskLockedError",
    # Events
    "AgentChangedEvent",
    "AgentDiedEvent",
    "AgentErrorEvent",
    "AgentFixCompleted",
    "AgentFixStarted",
    "AgentOutputEvent",
    "ApprovalDecision",
    "ApprovalRequested",
    "AutoVerifyCompleted",
    "BackMergeCompleted",
    "BackMergeReverted",
    "BufferingEmitter",
    "ChildCompleted",
    "ChildFailed",
    "ChildSpawned",
    "ChecklistGateEvaluated",
    "ChecklistItemGraded",
    "ChecklistItemUpdated",
    "ClarificationRequested",
    "ClarificationResponded",
    "AttemptUpdated",
    "ConflictResolved",
    "deserialize_event",
    "FanOutChildrenCreated",
    "FanOutChildrenReset",
    "FanOutChildRetried",
    "FanOutCompleted",
    "FanOutSpawned",
    "GradeDetail",
    "GradesEvaluated",
    "HealthCheckEvent",
    "ParentOversightFactsUpdated",
    "PersistentEventEmitter",
    "PruneApplied",
    "RunCreated",
    "RunDeleted",
    "RunMetadataUpdated",
    "RunStatusChanged",
    "RunStepBackward",
    "RunWorktreeCommitCompleted",
    "RunWorktreeCommitFailed",
    "RunWorktreeCommitRequested",
    "RunWorktreeCreationFailed",
    "RunWorktreeCreationRequested",
    "RunWorktreeResetCompleted",
    "RunWorktreeResetFailed",
    "RunWorktreeResetRequested",
    "RunWorktreeUpdated",
    "SignalEnqueued",
    "SignalProcessed",
    "StepCompleted",
    "StepCreated",
    "StepHumanApprovalRecorded",
    "StepIndexRewound",
    "StepSkipped",
    "TaskAttemptCreated",
    "TaskCreated",
    "TaskReverted",
    "TaskStatusChanged",
    "TestRunCompleted",
    "TestRunStarted",
    "WorkflowEvent",
    # Commands
    "CompleteRunWorktreeCommitCommand",
    "CompleteRunWorktreeResetCommand",
    "CreateFanOutChildrenCommand",
    "CreateRunCommand",
    "CreateTaskAttemptCommand",
    "CreateTaskCommand",
    "DeleteRunCommand",
    "FailRunWorktreeCommitCommand",
    "FailRunWorktreeResetCommand",
    "FailRunWorktreeCreationCommand",
    "InitialAttemptForRunCreate",
    "InitialStepForRunCreate",
    "InitialTaskForRunCreate",
    "RecordClarificationRequestCommand",
    "RecordStepHumanApprovalCommand",
    "RecordTaskRevertedCommand",
    "RequestRunWorktreeCommitCommand",
    "RequestRunWorktreeCreationCommand",
    "RequestRunWorktreeResetCommand",
    "ResetFanOutChildrenCommand",
    "RetryFanOutChildCommand",
    "RewindStepIndexCommand",
    "SetChecklistGradeCommand",
    "UpdateChecklistItemCommand",
    "UpdateLatestAttemptCommand",
    "UpdateParentOversightFactsCommand",
    "UpdateRunMetadataCommand",
    "UpdateRunStatusCommand",
    "UpdateRunWorktreeCommand",
    "UpdateTaskStatusCommand",
    "build_create_run_command",
    "expand_run_snapshot_for_projection",
    "handle_complete_run_worktree_commit",
    "handle_complete_run_worktree_reset",
    "handle_create_fan_out_children",
    "handle_create_run",
    "handle_create_task",
    "handle_create_task_attempt",
    "handle_delete_run",
    "handle_fail_run_worktree_commit",
    "handle_fail_run_worktree_creation",
    "handle_fail_run_worktree_reset",
    "handle_record_clarification_request",
    "handle_record_step_human_approval",
    "handle_record_task_reverted",
    "handle_request_run_worktree_commit",
    "handle_request_run_worktree_creation",
    "handle_request_run_worktree_reset",
    "handle_reset_fan_out_children",
    "handle_retry_fan_out_child",
    "handle_rewind_step_index",
    "handle_set_checklist_grade",
    "handle_update_checklist_item",
    "handle_update_latest_attempt",
    "handle_update_parent_oversight_facts",
    "handle_update_run_metadata",
    "handle_update_run_status",
    "handle_update_run_worktree",
    "handle_update_task_status",
    # Signals & Runtime
    "EventSignalTransport",
    "ExecutorCallbacks",
    "InMemorySignalTransport",
    "LoopAction",
    "NoTaskReason",
    "PendingSignal",
    "RunWorkflow",
    "SignalConsumer",
    "SignalForInactiveRunError",
    "SignalQueue",
    "SignalTransport",
    "WorkflowSignal",
    "build_registry",
    "resolve_no_task_action",
    "signal_handler",
    # Agent (prompts, templates, context, clarifications, auto-verify, summary cache)
    "AutoVerifyResult",
    "AutoVerifyRunner",
    "BuilderPrompt",
    "ClarificationAnswer",
    "ClarificationQuestion",
    "ClarificationRequest",
    "ClarificationResponse",
    "CompressedDecision",
    "CompressedDecisions",
    "ContextError",
    "LocalAutoVerifyRunner",
    "RecoveryPrompt",
    "SummaryCache",
    "TaskContextBuilder",
    "VerifierPrompt",
    "build_artifact_header",
    "compress_clarifications",
    "count_tokens",
    "decisions_from_config",
    "derive_output_path",
    "evaluate_auto_verify",
    "extract_section",
    "format_clarification_artifact",
    "run_auto_verify",
    "generate_builder_prompt",
    "generate_recovery_prompt",
    "generate_verifier_prompt",
    "get_task_context",
    "has_crashes",
    "resolve_artifact_path",
    "resolve_template",
    "resolve_variables",
    "truncate_to_tokens",
    # Service & Completion
    "DryRunResult",
    "GraphRunDriver",
    "GraphRunOutcome",
    "WorkflowService",
    "build_dry_run_context",
    "build_dry_run_prompt",
    "execute_dry_run",
    "find_step_config",
    "find_task_config",
    "get_step_by_id",
    "handle_run_completion",
    "parse_dry_run_response",
    # Delegation
    "DelegateCommand",
    "DelegateCommandKind",
    "DelegateResultEnvelope",
    "DelegatedWork",
    "DelegatedWorkStatus",
    "DelegationDecision",
    "DelegationDecisionKind",
    "DelegationPolicy",
    "DelegationRecord",
    "DelegationResultRecord",
    "DelegationReviewStateRecord",
    "DelegationRecorder",
    "DelegationStableState",
    "DelegationState",
    "FanOutDelegationPolicy",
    "FanOutFacts",
    "apply_delegate_command",
    "build_fan_out_facts",
    "work_from_fan_out_child",
    # Oversight reducer
    "APPEND_ONLY_OVERSIGHT_LIST_KEYS",
    "DURABLE_PARENT_OVERSIGHT_FACT_KEYS",
    "SET_UNION_OVERSIGHT_LIST_KEYS",
    "durable_parent_oversight_patch",
]


def __getattr__(name: str) -> Any:  # noqa: ANN401
    if name in {"GraphRunDriver", "GraphRunOutcome"}:
        from orchestrator.workflow.graph_driver import GraphRunDriver, GraphRunOutcome

        values = {
            "GraphRunDriver": GraphRunDriver,
            "GraphRunOutcome": GraphRunOutcome,
        }
        return values[name]
    if name in {"WorkflowService", "find_step_config", "find_task_config"}:
        from orchestrator.workflow.service import (
            WorkflowService,
            find_step_config,
            find_task_config,
        )

        values = {
            "WorkflowService": WorkflowService,
            "find_step_config": find_step_config,
            "find_task_config": find_task_config,
        }
        return values[name]
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
