"""Workflow engine and orchestration - all public symbols exhaustively re-exported."""

from orchestrator.workflow.artifacts import Artifact, ArtifactRegistry
from orchestrator.workflow.engine import (
    Clock,
    ConditionEvalError,
    ConditionEvaluator,
    DEFAULT_GRADE_ORDER,
    DefaultClock,
    EventEmitter,
    GateBlockedError,
    GateResult,
    GradeResult,
    InvalidTransitionError,
    NoOpEmitter,
    Parser,
    StepOutcome,
    Token,
    Tokenizer,
    TokenType,
    TransitionResult,
    VALID_TRANSITIONS,
    WorkflowEngine,
    WorkflowError,
    check_run_completion,
    check_step_progression,
    evaluate_checklist_gate,
    evaluate_condition,
    evaluate_gate,
    evaluate_grades,
    evaluate_transition_conditions,
    grade_meets_threshold,
    is_step_complete,
    step_has_failure,
    transition_after_verification,
    transition_from_approval,
    transition_from_clarification,
    transition_to_building,
    transition_to_pending_approval,
    transition_to_pending_clarification,
    transition_force_accept,
    transition_to_recovering,
    transition_to_verifying,
)
from orchestrator.workflow.engine.transitions import (
    _build_step_outcomes,  # pyright: ignore[reportPrivateUsage]
    _create_repeat_step_copies,  # pyright: ignore[reportPrivateUsage]
    _find_step_config,  # pyright: ignore[reportPrivateUsage]
    _get_variable_value_for_repeat,  # pyright: ignore[reportPrivateUsage]
    _parse_repeat_for_expression,  # pyright: ignore[reportPrivateUsage]
)
from orchestrator.workflow.locks import (
    InMemoryLockManager,
    LockManager,
    LockTimeoutError,
    TaskLockedError,
)
from orchestrator.workflow.events import (
    AgentChangedEvent,
    AgentDiedEvent,
    AgentErrorEvent,
    AgentFixCompleted,
    AgentFixStarted,
    AgentOutputEvent,
    ApprovalDecision,
    ApprovalRequested,
    AutoVerifyCompleted,
    BackMergeCompleted,
    BackMergeReverted,
    BufferingEmitter,
    ChildCompleted,
    ChildFailed,
    ChildSpawned,
    ChecklistGateEvaluated,
    ClarificationRequested,
    ClarificationResponded,
    ConflictResolved,
    FanOutCompleted,
    FanOutSpawned,
    GradeDetail,
    GradesEvaluated,
    HealthCheckEvent,
    PersistentEventEmitter,
    PruneApplied,
    RunStatusChanged,
    RunStepBackward,
    StepCompleted,
    StepSkipped,
    TaskReverted,
    TaskStatusChanged,
    TestRunCompleted,
    TestRunStarted,
    WorkflowEvent,
)
from orchestrator.workflow.signals import (
    DbSignalTransport,
    ExecutorCallbacks,
    InMemorySignalTransport,
    LoopAction,
    NoTaskReason,
    PendingSignal,
    RunWorkflow,
    SignalConsumer,
    SignalQueue,
    SignalTransport,
    WorkflowSignal,
    build_registry,
    resolve_no_task_action,
    signal_handler,
)

# Registry helpers live in consumer.py — not part of public API.
# Re-exported here so test files can import via orchestrator.workflow (required
# by the module-imports pre-commit hook). NOT in __all__. Business logic must
# not import these — enforced by the signal-routing pre-commit hook.
from orchestrator.workflow.signals.consumer import (
    has_active_workflow as has_active_workflow,  # consumer.py
    register_active_run as register_active_run,  # consumer.py
    unregister_active_run as unregister_active_run,  # consumer.py
)

from orchestrator.workflow.agent import (
    AutoVerifyResult,
    AutoVerifyRunner,
    BuilderPrompt,
    ClarificationAnswer,
    ClarificationQuestion,
    ClarificationRequest,
    ClarificationResponse,
    CompressedDecision,
    CompressedDecisions,
    ContextError,
    LocalAutoVerifyRunner,
    RecoveryPrompt,
    SummaryCache,
    TaskContextBuilder,
    VerifierPrompt,
    build_artifact_header,
    compress_clarifications,
    count_tokens,
    decisions_from_config,
    derive_output_path,
    evaluate_auto_verify,
    extract_section,
    format_clarification_artifact,
    run_auto_verify,
    generate_builder_prompt,
    generate_recovery_prompt,
    generate_verifier_prompt,
    get_task_context,
    has_crashes,
    resolve_artifact_path,
    resolve_template,
    resolve_variables,
    truncate_to_tokens,
)
from orchestrator.workflow.service import (
    SubmitEventRegistry,
    WorkflowService,
    find_step_config,
    find_task_config,
)
from orchestrator.workflow.completion import handle_run_completion
from orchestrator.workflow.dry_run import (
    DryRunResult,
    build_dry_run_context,
    build_dry_run_prompt,
    execute_dry_run,
    get_step_by_id,
    parse_dry_run_response,
)

__all__ = [
    # Artifacts
    "Artifact",
    "ArtifactRegistry",
    # Engine (errors, gates, grades, transitions, condition evaluation)
    "_build_step_outcomes",
    "_create_repeat_step_copies",
    "_find_step_config",
    "_get_variable_value_for_repeat",
    "_parse_repeat_for_expression",
    "Clock",
    "ConditionEvalError",
    "ConditionEvaluator",
    "DEFAULT_GRADE_ORDER",
    "DefaultClock",
    "EventEmitter",
    "GateBlockedError",
    "GateResult",
    "GradeResult",
    "InvalidTransitionError",
    "NoOpEmitter",
    "Parser",
    "StepOutcome",
    "Token",
    "Tokenizer",
    "TokenType",
    "TransitionResult",
    "VALID_TRANSITIONS",
    "WorkflowEngine",
    "WorkflowError",
    "check_run_completion",
    "check_step_progression",
    "evaluate_checklist_gate",
    "evaluate_condition",
    "evaluate_gate",
    "evaluate_grades",
    "evaluate_transition_conditions",
    "grade_meets_threshold",
    "is_step_complete",
    "step_has_failure",
    "transition_after_verification",
    "transition_from_approval",
    "transition_from_clarification",
    "transition_to_building",
    "transition_to_pending_approval",
    "transition_to_pending_clarification",
    "transition_force_accept",
    "transition_to_recovering",
    "transition_to_verifying",
    # Locks
    "InMemoryLockManager",
    "LockManager",
    "LockTimeoutError",
    "TaskLockedError",
    # Events
    "AgentChangedEvent",
    "AgentDiedEvent",
    "AgentErrorEvent",
    "AgentFixCompleted",
    "AgentFixStarted",
    "AgentOutputEvent",
    "ApprovalDecision",
    "ApprovalRequested",
    "AutoVerifyCompleted",
    "BackMergeCompleted",
    "BackMergeReverted",
    "BufferingEmitter",
    "ChildCompleted",
    "ChildFailed",
    "ChildSpawned",
    "ChecklistGateEvaluated",
    "ClarificationRequested",
    "ClarificationResponded",
    "ConflictResolved",
    "FanOutCompleted",
    "FanOutSpawned",
    "GradeDetail",
    "GradesEvaluated",
    "HealthCheckEvent",
    "PersistentEventEmitter",
    "PruneApplied",
    "RunStatusChanged",
    "RunStepBackward",
    "StepCompleted",
    "StepSkipped",
    "TaskReverted",
    "TaskStatusChanged",
    "TestRunCompleted",
    "TestRunStarted",
    "WorkflowEvent",
    # Signals & Runtime
    "DbSignalTransport",
    "ExecutorCallbacks",
    "InMemorySignalTransport",
    "LoopAction",
    "NoTaskReason",
    "PendingSignal",
    "RunWorkflow",
    "SignalConsumer",
    "SignalQueue",
    "SignalTransport",
    "WorkflowSignal",
    "build_registry",
    "resolve_no_task_action",
    "signal_handler",
    # Agent (prompts, templates, context, clarifications, auto-verify, summary cache)
    "AutoVerifyResult",
    "AutoVerifyRunner",
    "BuilderPrompt",
    "ClarificationAnswer",
    "ClarificationQuestion",
    "ClarificationRequest",
    "ClarificationResponse",
    "CompressedDecision",
    "CompressedDecisions",
    "ContextError",
    "LocalAutoVerifyRunner",
    "RecoveryPrompt",
    "SummaryCache",
    "TaskContextBuilder",
    "VerifierPrompt",
    "build_artifact_header",
    "compress_clarifications",
    "count_tokens",
    "decisions_from_config",
    "derive_output_path",
    "evaluate_auto_verify",
    "extract_section",
    "format_clarification_artifact",
    "run_auto_verify",
    "generate_builder_prompt",
    "generate_recovery_prompt",
    "generate_verifier_prompt",
    "get_task_context",
    "has_crashes",
    "resolve_artifact_path",
    "resolve_template",
    "resolve_variables",
    "truncate_to_tokens",
    # Service & Completion
    "DryRunResult",
    "SubmitEventRegistry",
    "WorkflowService",
    "build_dry_run_context",
    "build_dry_run_prompt",
    "execute_dry_run",
    "find_step_config",
    "find_task_config",
    "get_step_by_id",
    "handle_run_completion",
    "parse_dry_run_response",
]
