"""Clarification models and artifact generation (pure functions)."""

from datetime import datetime
from typing import Any

from pydantic import BaseModel


class ClarificationQuestion(BaseModel):
    """A question from the builder needing human input."""

    id: str
    question: str
    context: str
    options: list[str]  # Multi-choice options (2-4)


class ClarificationAnswer(BaseModel):
    """Human's answer to a clarification question."""

    question_id: str
    selected_option: str | None = None
    free_text: str | None = None
    answered_by: str
    answered_at: datetime


class ClarificationRequest(BaseModel):
    """A set of questions from builder needing answers."""

    id: str
    run_id: str
    task_id: str
    attempt_num: int
    questions: list[ClarificationQuestion]
    created_at: datetime
    responded_at: datetime | None = None


class ClarificationResponse(BaseModel):
    """Human's answers to a clarification request."""

    request_id: str
    answers: list[ClarificationAnswer]
    responded_at: datetime


def format_clarification_artifact(
    request: ClarificationRequest,
    response: ClarificationResponse,
    step_id: str,
    clarification_number: int,
) -> str:
    """Format clarification Q&A as markdown section for artifact file.

    Pure function - no I/O.
    """
    lines = [
        f"## Clarification {clarification_number} (Step {step_id}, Attempt {request.attempt_num})",
        f"**Requested:** {request.created_at.isoformat()}",
        "",
    ]

    for i, q in enumerate(request.questions, 1):
        answer = next((a for a in response.answers if a.question_id == q.id), None)

        lines.append(f"### Q{i}: {q.question}")
        lines.append(f"**Context:** {q.context}")
        lines.append("**Options:**")
        for j, opt in enumerate(q.options, 1):
            lines.append(f"{j}. {opt}")
        lines.append("")

        if answer:
            if answer.free_text:
                lines.append(f"**Answer:** (custom) {answer.free_text}")
            elif answer.selected_option:
                lines.append(f"**Answer:** {answer.selected_option}")
            lines.append(f"**Answered by:** {answer.answered_by}")
            lines.append(f"**Answered at:** {answer.answered_at.isoformat()}")
        lines.append("")

    return "\n".join(lines)


def build_artifact_header() -> str:
    """Build the header for a new clarifications artifact file."""
    return """# Clarifications Log
<!-- Auto-generated by Orchestrator. Referenced in build/verify phases. -->

"""


def resolve_artifact_path(template: str, config: dict[str, Any]) -> str:
    """Resolve {{variable}} placeholders in artifact path template.

    Pure function - no I/O.
    """
    result = template
    for key, value in config.items():
        result = result.replace(f"{{{{{key}}}}}", str(value))
    return result
