"""Representative current-producer payloads for catalog contract tests.

These are intentionally literal payload maps rather than generated values: a
catalog addition must make its producer contract visible in this one place.
"""

from __future__ import annotations

from datetime import UTC, datetime
from typing import Final


_CANDIDATE_RECORD: Final[dict[str, object]] = {
    "record_id": "candidate-1",
    "record_kind": "output",
    "record_type": "candidate",
    "producer_node_id": "worker-1",
    "port": "candidate",
    "schema": "ImplementationCandidate",
    "candidate_id": "candidate-1",
    "value": {"summary": "implemented"},
}
_FILE_STATE_RECORD: Final[dict[str, object]] = {
    "record_id": "file-state-1",
    "record_kind": "file_state",
    "record_type": "file_state",
    "producer_node_id": "worker-1",
    "port": "file_state",
    "schema": "FileStateRecord",
}
_FILE_ENTRY: Final[dict[str, object]] = {"path": "build/output.txt", "status": "untracked"}
_GATEKEEPER_VERDICT: Final[dict[str, object]] = {
    "path": "build/output.txt",
    "classification": "build_output",
    "confidence": 0.9,
    "rationale": "generated output",
    "model_id": "gatekeeper-1",
    "input_tokens": 1,
    "output_tokens": 1,
    "cache_read_tokens": 0,
    "cache_write_tokens": 0,
    "cost_usd": 0.01,
    "wall_time_ms": 1,
}
_OBSERVED_AT: Final[datetime] = datetime(2026, 7, 12, 12, tzinfo=UTC)
_EXPIRES_AT: Final[datetime] = datetime(2026, 7, 12, 13, tzinfo=UTC)

EVENT_SAMPLES: Final[dict[str, dict[str, object]]] = {
    "run_lifecycle_changed": {"to_state": "running"},
    "command_rejected": {"command_type": "start", "reason": "blocked"},
    "callback_accepted": {
        "node_id": "node-1",
        "idempotency_key": "key-1",
        "payload": {},
        "reason": "accepted",
    },
    "callback_rejected_stale": {
        "node_id": "node-1",
        "idempotency_key": "key-1",
        "payload": {},
        "reason": "stale",
    },
    "callback_rejected_conflict": {
        "node_id": "node-1",
        "idempotency_key": "key-1",
        "payload": {},
        "reason": "conflict",
    },
    "callback_duplicate_returned": {
        "node_id": "node-1",
        "idempotency_key": "key-1",
        "payload": {},
        "reason": "duplicate",
        "prior_result": None,
    },
    "runtime_retry_scheduled": {
        "node_id": "node-1",
        "lease_id": "lease-1",
        "generation": 1,
        "policy": "retry",
        "reason": "timeout",
    },
    "heartbeat_recorded": {
        "node_id": "node-1",
        "lease_id": "lease-1",
        "lease_generation": 1,
        "observed_at": _OBSERVED_AT,
    },
    "agent_died": {
        "lease_id": "lease-1",
        "node_id": "node-1",
        "generation": 1,
        "reason": "process_died",
    },
    "agent_dispatch_requested": {
        "lease_granted_event_id": "event-1",
        "lease_id": "lease-1",
        "node_id": "node-1",
        "generation": 1,
        "execution_id": "execution-1",
        "base_snapshot_id": "snapshot-1",
        "resource_claims": [],
    },
    "output_record_accepted": {"record": _CANDIDATE_RECORD},
    "verification_passed": {
        "node_id": "node-1",
        "verifier_node_id": "verifier-1",
        "candidate_id": "candidate-1",
        "outcome": "passed",
        "record_id": "record-1",
    },
    "verification_failed": {
        "node_id": "node-1",
        "verifier_node_id": "verifier-1",
        "candidate_id": "candidate-1",
        "outcome": "failed",
        "record_id": "record-1",
    },
    "node_created": {"node_id": "node-1", "kind": "worker"},
    "node_state_changed": {"node_id": "node-1", "new_state": "running"},
    "node_retired": {"node_id": "node-1"},
    "node_ready": {"node_id": "node-1"},
    "node_deferred": {"node_id": "node-1", "reason": "waiting"},
    "node_authority_changed": {"node_id": "node-1"},
    "plan_region_marked_suspect": {"region_node_ids": ["node-1"], "reason": "invalidated"},
    "edge_created": {
        "edge_id": "edge-1",
        "from_node_id": "node-1",
        "from_port": "output",
        "to_node_id": "node-2",
        "to_port": "input",
    },
    "input_bound": {
        "edge_id": "edge-1",
        "to_node_id": "node-2",
        "to_port": "input",
        "record_ids": ["record-1"],
        "bound_at_position": 1,
    },
    "session_state_changed": {
        "session_id": "session-1",
        "state": "suspended",
        "node_id": "node-1",
        "lease_generation": 1,
        "carryover_record_id": None,
    },
    "dead_input_detected": {"node_id": "node-1", "reason": "source retired"},
    "revision_created": {},
    "lease_granted": {
        "lease_id": "lease-1",
        "node_id": "node-1",
        "generation": 1,
        "execution_id": "execution-1",
        "base_snapshot_id": "snapshot-1",
        "expires_at": _EXPIRES_AT,
        "resource_claims": (),
    },
    "lease_renewed": {
        "lease_id": "lease-1",
        "node_id": "node-1",
        "generation": 1,
        "execution_id": "execution-1",
        "observed_at": _OBSERVED_AT,
        "expires_at": _EXPIRES_AT,
    },
    "lease_released": {"lease_id": "lease-1", "node_id": "node-1", "generation": 1},
    "lease_revoked": {
        "lease_id": "lease-1",
        "node_id": "node-1",
        "generation": 1,
        "execution_id": "execution-1",
        "trigger": "cancel",
        "reason": "cancelled",
    },
    "lease_expired": {
        "lease_id": "lease-1",
        "node_id": "node-1",
        "generation": 1,
        "execution_id": "execution-1",
        "expires_at": _EXPIRES_AT,
        "reason": "expired",
    },
    "graph_patch_accepted": {
        "patch_id": "patch-1",
        "base_graph_position": 1,
        "actor_role": "planner",
        "proposed_by_node_id": "node-1",
        "successor_planner_node_ids": [],
    },
    "graph_patch_rejected": {
        "patch_id": "patch-1",
        "base_graph_position": 1,
        "actor_role": "planner",
        "proposed_by_node_id": "node-1",
        "reason": "conflict",
    },
    "appeal_opened": {
        "node_id": "appeal-1",
        "appealed_node_id": "node-1",
        "appeal_type": "invalid_test",
    },
    "approval_decision_recorded": {
        "node_id": "node-1",
        "decision": "approved",
        "decider": "operator",
    },
    "authority_decision_recorded": {
        "node_id": "node-1",
        "decision": "granted",
        "decider": "operator",
    },
    "oversight_decision_recorded": {
        "node_id": "node-1",
        "decision": "accepted",
        "decider": "operator",
    },
    "requirement_revision_recorded": {"requirement_id": "requirement-1", "version_id": "version-1"},
    "support_evidence_recorded": {
        "support_id": "support-1",
        "evidence_id": "evidence-1",
        "requirement_id": "requirement-1",
        "requirement_version_id": "version-1",
    },
    "file_state_accepted": _FILE_STATE_RECORD,
    "file_state_rejected": {
        "node_id": "node-1",
        "run_id": "run-1",
        "execution_id": "execution-1",
        "lease_id": "lease-1",
        "lease_generation": 1,
        "classifications": [],
        "rejected_paths": [],
    },
    "gatekeeper_verdict_recorded": {
        "file_state_record_id": "file-state-1",
        "execution_id": "execution-1",
        "verdicts": (_GATEKEEPER_VERDICT,),
        "resolved_count": 1,
    },
    "gatekeeper_cost_recorded": {
        "file_state_record_id": "file-state-1",
        "execution_id": "execution-1",
        "consult_id": "consult-1",
        "model_id": "gatekeeper-1",
        "input_tokens": 1,
        "output_tokens": 1,
        "cache_read_tokens": 0,
        "cache_write_tokens": 0,
        "cost_usd": 0.01,
        "wall_time_ms": 1,
        "item_count": 1,
    },
    "cleanup_requested": {
        "cleanup_id": "cleanup-1",
        "file_state_record_id": "file-state-1",
        "paths": ("secret.txt",),
        "authority": "gatekeeper",
        "execution_id": "execution-1",
    },
    "cleanup_applied": {
        "cleanup_id": "cleanup-1",
        "file_state_record_id": "file-state-1",
        "superseding_record_id": "file-state-2",
        "old_snapshot_id": "snapshot-1",
        "new_snapshot_id": "snapshot-2",
        "paths": ("secret.txt",),
        "authority": "gatekeeper",
        "reason": "secret removed",
        "execution_id": "execution-1",
        "deleted_snapshot_ref": True,
        "resolved_count": 1,
    },
}

COMMAND_SAMPLES: Final[dict[str, dict[str, object]]] = {
    "accept_run": {},
    "start": {},
    "pause": {},
    "resume": {},
    "cancel": {},
    "complete": {},
    "fail": {"reason": "command_failed"},
    "record_heartbeat": {"node_id": "node-1", "lease_id": "lease-1", "lease_generation": 1},
    "agent_died": {"lease_id": "lease-1"},
    "acknowledge_start": {
        "node_id": "node-1",
        "lease_id": "lease-1",
        "lease_generation": 1,
        "execution_id": "execution-1",
    },
    "submit_callback": {
        "node_id": "node-1",
        "execution_id": "execution-1",
        "lease_id": "lease-1",
        "lease_generation": 1,
        "base_snapshot_id": "snapshot-1",
        "observed_graph_position": 1,
        "idempotency_key": "key-1",
    },
    "raise_appeal": {"node_id": "node-1", "appeal_type": "invalid_test"},
    "record_decision": {
        "decision_type": "approval",
        "node_id": "node-1",
        "decision": "approved",
        "decider": "operator",
    },
    "record_requirement_revision": {"requirement_id": "requirement-1", "version_id": "version-1"},
    "record_support_evidence": {
        "support_id": "support-1",
        "evidence_id": "evidence-1",
        "requirement_id": "requirement-1",
        "requirement_version_id": "version-1",
    },
    "seed_compiled_events": {"events": ()},
    "schedule_tick": {"lease_seconds": 30, "max_grants": 1},
    "reconcile": {},
    "submit_patch": {
        "patch_id": "patch-1",
        "base_graph_position": 1,
        "actor_role": "planner",
        "proposed_by_node_id": "node-1",
        "ops": [{"op": "retire_node", "node_id": "node-1"}],
    },
    "evaluate_join": {"node_id": "node-1"},
    "evaluate_final_gate": {"node_id": "node-1"},
    "record_gatekeeper_verdicts": {
        "file_state_record_id": "file-state-1",
        "execution_id": "execution-1",
        "consult_id": "consult-1",
        "model_id": "gatekeeper-1",
        "verdicts": [_GATEKEEPER_VERDICT],
    },
    "record_cleanup_applied": {
        "cleanup_id": "cleanup-1",
        "superseding_file_state_record": _FILE_STATE_RECORD,
        "deleted_snapshot_ref": True,
    },
}
