"""Effectful runtime adapters for the pure execution graph kernel."""

from orchestrator.graph_runtime.controller import GraphCommandResult, GraphController
from orchestrator.graph_runtime.dispatch import (
    CHECK_OUTPUT_EXTERNALIZE_BYTES,
    CHECK_OUTPUT_TAIL_CHARS,
    GraphAgentFactory,
    GraphDispatchContext,
    GraphDispatchExecutor,
    GraphProcessRegistry,
    MANAGED_LEASE_TTL_SECONDS,
    RunnerOwnedProcessRegistry,
    StaticGraphAgentFactory,
    assemble_graph_dispatch_context,
    build_graph_runtime,
    reconcile_runtime,
)
from orchestrator.graph_runtime.errors import (
    CacheScanBudgetExceededError,
    CompromisedFileStateError,
    GraphRuntimeError,
    GraphEventEnvelopeTooLargeError,
    OutboxAppendError,
    ProcessQuiescenceError,
    RecoveryCompletionRejectedError,
    RecoveryEventError,
    RecoveryRestoreError,
    StaleProjectionError,
)
from orchestrator.graph_runtime.file_state import (
    CleanupApplication,
    FileStateBoundaryResult,
    WorktreeFileStateBaseline,
    apply_cleanup_requested,
    capture_worktree_file_state_baseline,
    capture_file_state_boundary,
    collect_worktree_status,
    file_state_output_record,
)
from orchestrator.graph_runtime.gatekeeper import (
    ClaudeGatekeeperClassifier,
    GatekeeperVerdict,
    ResidueClassifier,
    ResidueMetadata,
    metadata_from_file_state_record,
    policy_with_pattern_library,
)
from orchestrator.graph_runtime.horizon_templates import (
    HORIZON_REGION_PURPOSES,
    horizon_region_templates,
    instantiate_horizon_template,
)
from orchestrator.graph_runtime.outbox import (
    OUTBOX_MAINTENANCE_BATCH_LIMIT,
    OutboxDispatcher,
    OutboxItem,
    SideEffectExecutor,
)
from orchestrator.graph_runtime.prompts import (
    hydrate_artifact_excerpt,
    planner_evidence,
    render_graph_node_prompt,
    summarize_graph_node_prompt,
)
from orchestrator.graph_runtime.recovery import RecoveryReport, recover, reconcile_graph
from orchestrator.graph_runtime.reliable_plan_scenarios import (
    ReliablePlanProductPathRunner,
    ReliablePlanQualificationRun,
    ReliablePlanScenarioAssertionError,
    run_reliable_plan_product_path_scenarios,
)
from orchestrator.graph_runtime.reliable_plan_qualification import (
    consume_reliable_plan_qualification,
    has_caller_supplied_reliable_plan_authorization,
    issue_reliable_plan_qualification,
    require_reliable_plan_qualification_for_run,
    sealed_reliable_plan_run_authorization,
    verified_reliable_plan_seed_config,
)
from orchestrator.graph_runtime.seeding import SeedRunResult, seed_run
from orchestrator.graph_runtime.store import (
    BoundedGraphPage,
    GraphExpectedPositionMismatch,
    GraphReadBudget,
    GraphReadContract,
    GraphReadModelUnavailable,
    GRAPH_READ_CONTRACTS,
    GraphEventStore,
    GraphPatchAttemptPage,
    bound_graph_json,
    bound_node_detail_owner,
    graph_aggregate_id,
)

__all__ = [
    "GraphCommandResult",
    "BoundedGraphPage",
    "CHECK_OUTPUT_EXTERNALIZE_BYTES",
    "CHECK_OUTPUT_TAIL_CHARS",
    "GraphAgentFactory",
    "GraphController",
    "GraphDispatchContext",
    "GraphDispatchExecutor",
    "GraphProcessRegistry",
    "MANAGED_LEASE_TTL_SECONDS",
    "GraphEventStore",
    "GraphExpectedPositionMismatch",
    "GraphReadBudget",
    "GraphReadContract",
    "GraphReadModelUnavailable",
    "GRAPH_READ_CONTRACTS",
    "GraphPatchAttemptPage",
    "bound_graph_json",
    "bound_node_detail_owner",
    "graph_aggregate_id",
    "GraphRuntimeError",
    "GraphEventEnvelopeTooLargeError",
    "HORIZON_REGION_PURPOSES",
    "CompromisedFileStateError",
    "CacheScanBudgetExceededError",
    "CleanupApplication",
    "FileStateBoundaryResult",
    "WorktreeFileStateBaseline",
    "ClaudeGatekeeperClassifier",
    "GatekeeperVerdict",
    "OutboxAppendError",
    "OUTBOX_MAINTENANCE_BATCH_LIMIT",
    "ProcessQuiescenceError",
    "RecoveryCompletionRejectedError",
    "RecoveryEventError",
    "RecoveryRestoreError",
    "OutboxDispatcher",
    "OutboxItem",
    "RecoveryReport",
    "ReliablePlanProductPathRunner",
    "ReliablePlanQualificationRun",
    "ReliablePlanScenarioAssertionError",
    "RunnerOwnedProcessRegistry",
    "ResidueClassifier",
    "ResidueMetadata",
    "SeedRunResult",
    "SideEffectExecutor",
    "StaleProjectionError",
    "StaticGraphAgentFactory",
    "assemble_graph_dispatch_context",
    "build_graph_runtime",
    "apply_cleanup_requested",
    "capture_file_state_boundary",
    "capture_worktree_file_state_baseline",
    "collect_worktree_status",
    "file_state_output_record",
    "horizon_region_templates",
    "hydrate_artifact_excerpt",
    "instantiate_horizon_template",
    "metadata_from_file_state_record",
    "planner_evidence",
    "render_graph_node_prompt",
    "summarize_graph_node_prompt",
    "policy_with_pattern_library",
    "recover",
    "reconcile_graph",
    "reconcile_runtime",
    "run_reliable_plan_product_path_scenarios",
    "consume_reliable_plan_qualification",
    "has_caller_supplied_reliable_plan_authorization",
    "issue_reliable_plan_qualification",
    "require_reliable_plan_qualification_for_run",
    "sealed_reliable_plan_run_authorization",
    "verified_reliable_plan_seed_config",
    "seed_run",
]
